/*-
 * ========================LICENSE_START=================================
 * d16b-edifact-binding
 * %%
 * Copyright (C) 2020 - 2024 Smooks
 * %%
 * Licensed under the terms of the Apache License Version 2.0, or
 * the GNU Lesser General Public License version 3.0 or later.
 * 
 * SPDX-License-Identifier: Apache-2.0 OR LGPL-3.0-or-later
 * 
 * ======================================================================
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * ======================================================================
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * =========================LICENSE_END==================================
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.17 at 06:20:44 PM UTC 
//


package org.smooks.edifact.binding.d16b;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BGM-BeginningOfMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BGM-BeginningOfMessage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="C002" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}C002-DocumentMessageName" minOccurs="0"/&gt;
 *         &lt;element name="C106" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}C106-DocumentMessageIdentification" minOccurs="0"/&gt;
 *         &lt;element name="E1225" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E1225-MessageFunctionCode" minOccurs="0"/&gt;
 *         &lt;element name="E4343" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E4343-ResponseTypeCode" minOccurs="0"/&gt;
 *         &lt;element name="E1373" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E1373-DocumentStatusCode" minOccurs="0"/&gt;
 *         &lt;element name="E3453" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E3453-LanguageNameCode" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BGM-BeginningOfMessage", propOrder = {
    "c002",
    "c106",
    "e1225",
    "e4343",
    "e1373",
    "e3453"
})
public class BGMBeginningOfMessage {

    @XmlElement(name = "C002")
    protected C002DocumentMessageName c002;
    @XmlElement(name = "C106")
    protected C106DocumentMessageIdentification c106;
    @XmlElement(name = "E1225")
    protected String e1225;
    @XmlElement(name = "E4343")
    @XmlSchemaType(name = "string")
    protected E4343ResponseTypeCode e4343;
    @XmlElement(name = "E1373")
    protected String e1373;
    @XmlElement(name = "E3453")
    protected String e3453;

    /**
     * Gets the value of the c002 property.
     * 
     * @return
     *     possible object is
     *     {@link C002DocumentMessageName }
     *     
     */
    public C002DocumentMessageName getC002() {
        return c002;
    }

    /**
     * Sets the value of the c002 property.
     * 
     * @param value
     *     allowed object is
     *     {@link C002DocumentMessageName }
     *     
     */
    public void setC002(C002DocumentMessageName value) {
        this.c002 = value;
    }

    /**
     * Gets the value of the c106 property.
     * 
     * @return
     *     possible object is
     *     {@link C106DocumentMessageIdentification }
     *     
     */
    public C106DocumentMessageIdentification getC106() {
        return c106;
    }

    /**
     * Sets the value of the c106 property.
     * 
     * @param value
     *     allowed object is
     *     {@link C106DocumentMessageIdentification }
     *     
     */
    public void setC106(C106DocumentMessageIdentification value) {
        this.c106 = value;
    }

    /**
     * Gets the value of the e1225 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE1225() {
        return e1225;
    }

    /**
     * Sets the value of the e1225 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE1225(String value) {
        this.e1225 = value;
    }

    /**
     * Gets the value of the e4343 property.
     * 
     * @return
     *     possible object is
     *     {@link E4343ResponseTypeCode }
     *     
     */
    public E4343ResponseTypeCode getE4343() {
        return e4343;
    }

    /**
     * Sets the value of the e4343 property.
     * 
     * @param value
     *     allowed object is
     *     {@link E4343ResponseTypeCode }
     *     
     */
    public void setE4343(E4343ResponseTypeCode value) {
        this.e4343 = value;
    }

    /**
     * Gets the value of the e1373 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE1373() {
        return e1373;
    }

    /**
     * Sets the value of the e1373 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE1373(String value) {
        this.e1373 = value;
    }

    /**
     * Gets the value of the e3453 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE3453() {
        return e3453;
    }

    /**
     * Sets the value of the e3453 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE3453(String value) {
        this.e3453 = value;
    }

    public BGMBeginningOfMessage withC002(C002DocumentMessageName value) {
        setC002(value);
        return this;
    }

    public BGMBeginningOfMessage withC106(C106DocumentMessageIdentification value) {
        setC106(value);
        return this;
    }

    public BGMBeginningOfMessage withE1225(String value) {
        setE1225(value);
        return this;
    }

    public BGMBeginningOfMessage withE4343(E4343ResponseTypeCode value) {
        setE4343(value);
        return this;
    }

    public BGMBeginningOfMessage withE1373(String value) {
        setE1373(value);
        return this;
    }

    public BGMBeginningOfMessage withE3453(String value) {
        setE3453(value);
        return this;
    }

}
