/*-
 * ========================LICENSE_START=================================
 * d16b-edifact-binding
 * %%
 * Copyright (C) 2020 - 2024 Smooks
 * %%
 * Licensed under the terms of the Apache License Version 2.0, or
 * the GNU Lesser General Public License version 3.0 or later.
 * 
 * SPDX-License-Identifier: Apache-2.0 OR LGPL-3.0-or-later
 * 
 * ======================================================================
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * ======================================================================
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * =========================LICENSE_END==================================
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.17 at 06:20:44 PM UTC 
//


package org.smooks.edifact.binding.d16b;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for C784-FootnoteIdentification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="C784-FootnoteIdentification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="E9432" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E9432-FootnoteIdentifier"/&gt;
 *         &lt;element name="E7405" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E7405-ObjectIdentificationCodeQualifier" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "C784-FootnoteIdentification", propOrder = {
    "e9432",
    "e7405"
})
public class C784FootnoteIdentification {

    @XmlElement(name = "E9432", required = true)
    protected String e9432;
    @XmlElement(name = "E7405")
    @XmlSchemaType(name = "string")
    protected E7405ObjectIdentificationCodeQualifier e7405;

    /**
     * Gets the value of the e9432 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE9432() {
        return e9432;
    }

    /**
     * Sets the value of the e9432 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE9432(String value) {
        this.e9432 = value;
    }

    /**
     * Gets the value of the e7405 property.
     * 
     * @return
     *     possible object is
     *     {@link E7405ObjectIdentificationCodeQualifier }
     *     
     */
    public E7405ObjectIdentificationCodeQualifier getE7405() {
        return e7405;
    }

    /**
     * Sets the value of the e7405 property.
     * 
     * @param value
     *     allowed object is
     *     {@link E7405ObjectIdentificationCodeQualifier }
     *     
     */
    public void setE7405(E7405ObjectIdentificationCodeQualifier value) {
        this.e7405 = value;
    }

    public C784FootnoteIdentification withE9432(String value) {
        setE9432(value);
        return this;
    }

    public C784FootnoteIdentification withE7405(E7405ObjectIdentificationCodeQualifier value) {
        setE7405(value);
        return this;
    }

}
