/*-
 * ========================LICENSE_START=================================
 * d16b-edifact-binding
 * %%
 * Copyright (C) 2020 - 2024 Smooks
 * %%
 * Licensed under the terms of the Apache License Version 2.0, or
 * the GNU Lesser General Public License version 3.0 or later.
 * 
 * SPDX-License-Identifier: Apache-2.0 OR LGPL-3.0-or-later
 * 
 * ======================================================================
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * ======================================================================
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * =========================LICENSE_END==================================
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.17 at 06:20:44 PM UTC 
//


package org.smooks.edifact.binding.d16b;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GIR-RelatedIdentificationNumbers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GIR-RelatedIdentificationNumbers"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="E7297" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E7297-SetTypeCodeQualifier"/&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="C206" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}C206-IdentificationNumber" maxOccurs="5"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GIR-RelatedIdentificationNumbers", propOrder = {
    "e7297",
    "c206"
})
public class GIRRelatedIdentificationNumbers {

    @XmlElement(name = "E7297", required = true)
    protected String e7297;
    @XmlElement(name = "C206", required = true, nillable = true)
    protected List<C206IdentificationNumber> c206;

    /**
     * Gets the value of the e7297 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE7297() {
        return e7297;
    }

    /**
     * Sets the value of the e7297 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE7297(String value) {
        this.e7297 = value;
    }

    /**
     * Gets the value of the c206 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the c206 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getC206().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link C206IdentificationNumber }
     * 
     * 
     */
    public List<C206IdentificationNumber> getC206() {
        if (c206 == null) {
            c206 = new ArrayList<C206IdentificationNumber>();
        }
        return this.c206;
    }

    public GIRRelatedIdentificationNumbers withE7297(String value) {
        setE7297(value);
        return this;
    }

    public GIRRelatedIdentificationNumbers withC206(C206IdentificationNumber... values) {
        if (values!= null) {
            for (C206IdentificationNumber value: values) {
                getC206().add(value);
            }
        }
        return this;
    }

    public GIRRelatedIdentificationNumbers withC206(Collection<C206IdentificationNumber> values) {
        if (values!= null) {
            getC206().addAll(values);
        }
        return this;
    }

}
