//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.22 at 09:46:08 AM CET 
//


package no.kith.xmlstds.felleskomponent1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import no.kith.xmlstds.CV;


/**
 * Identifikasjon og type identifikasjon.
 * 
 * <p>Java class for Ident complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ident"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TypeId" type="{http://www.kith.no/xmlstds}CV"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ident", propOrder = {
    "id",
    "typeId"
})
public final class Ident {

    @XmlElement(name = "Id", required = true)
    private final String id;
    @XmlElement(name = "TypeId", required = true)
    private final CV typeId;

    public Ident(final String id, final CV typeId) {
        this.id = id;
        this.typeId = typeId;
    }

    /**
     * Used by JAX-B
     * 
     */
    protected Ident() {
        this.id = null;
        this.typeId = null;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Gets the value of the typeId property.
     * 
     * @return
     *     possible object is
     *     {@link CV }
     *     
     */
    public CV getTypeId() {
        return typeId;
    }

    public static Ident.IdentBuilder identBuilder() {
        return new Ident.IdentBuilder();
    }

    public static class IdentBuilder {

        private String id;
        private CV typeId;

        public Ident.IdentBuilder withId(final String id) {
            this.id = id;
            return this;
        }

        public Ident.IdentBuilder withTypeId(final CV typeId) {
            this.typeId = typeId;
            return this;
        }

        public Ident build() {
            if (id == null) {
                throw new NullPointerException("Required field 'id' have to be assigned a value.");
            }
            if (typeId == null) {
                throw new NullPointerException("Required field 'typeId' have to be assigned a value.");
            }
            return new Ident(id, typeId);
        }

    }

}
