//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.22 at 09:42:06 AM CET 
//


package no.kith.xmlstds;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for REAL complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="REAL"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="V" type="{http://www.w3.org/2001/XMLSchema}double" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REAL")
public final class REAL {

    @XmlAttribute(name = "V")
    private final Double v;

    public REAL(final Double v) {
        this.v = v;
    }

    /**
     * Used by JAX-B
     * 
     */
    protected REAL() {
        this.v = null;
    }

    /**
     * Gets the value of the v property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getV() {
        return v;
    }

    public static REAL.REALBuilder REALBuilder() {
        return new REAL.REALBuilder();
    }

    public static class REALBuilder {

        private Double v;

        public REAL.REALBuilder withV(final Double v) {
            this.v = v;
            return this;
        }

        public REAL build() {
            return new REAL(v);
        }

    }

}
