/*-
 * ========================LICENSE_START=================================
 * d16b-edifact-binding
 * %%
 * Copyright (C) 2020 - 2024 Smooks
 * %%
 * Licensed under the terms of the Apache License Version 2.0, or
 * the GNU Lesser General Public License version 3.0 or later.
 * 
 * SPDX-License-Identifier: Apache-2.0 OR LGPL-3.0-or-later
 * 
 * ======================================================================
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * ======================================================================
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * =========================LICENSE_END==================================
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.17 at 06:20:44 PM UTC 
//


package org.smooks.edifact.binding.d16b;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CONWQD complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CONWQD"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="BGM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}BGM-BeginningOfMessage"/&gt;
 *           &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="2" minOccurs="0"/&gt;
 *           &lt;element name="AUT" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}AUT-AuthenticationResult" maxOccurs="2" minOccurs="0"/&gt;
 *           &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" maxOccurs="5" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="SegGrp-1" maxOccurs="10" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference"/&gt;
 *                     &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="5" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SegGrp-2" maxOccurs="10" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="NAD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}NAD-NameAndAddress"/&gt;
 *                     &lt;element name="LOC" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LOC-PlaceLocationIdentification" maxOccurs="99" minOccurs="0"/&gt;
 *                     &lt;element name="FII" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FII-FinancialInstitutionInformation" maxOccurs="5" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;element name="SegGrp-3" maxOccurs="10" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference"/&gt;
 *                               &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="5" minOccurs="0"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="SegGrp-4" maxOccurs="5" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="DOC" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DOC-DocumentMessageDetails"/&gt;
 *                               &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="5" minOccurs="0"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="SegGrp-5" maxOccurs="5" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="CTA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}CTA-ContactInformation"/&gt;
 *                               &lt;element name="COM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}COM-CommunicationContact" maxOccurs="5" minOccurs="0"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SegGrp-6" maxOccurs="9999"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="BII" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}BII-StructureIdentification"/&gt;
 *                     &lt;element name="QTY" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}QTY-Quantity" maxOccurs="3" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;element name="SegGrp-7" maxOccurs="99" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference"/&gt;
 *                               &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" minOccurs="0"/&gt;
 *                               &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" minOccurs="0"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="SegGrp-8" maxOccurs="999" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="LIN" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LIN-LineItem"/&gt;
 *                               &lt;element name="GEI" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}GEI-ProcessingInformation"/&gt;
 *                               &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" minOccurs="0"/&gt;
 *                             &lt;/sequence&gt;
 *                             &lt;element name="SegGrp-9" maxOccurs="10" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;sequence&gt;
 *                                         &lt;element name="QTY" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}QTY-Quantity"/&gt;
 *                                         &lt;element name="GEI" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}GEI-ProcessingInformation" minOccurs="0"/&gt;
 *                                         &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference" minOccurs="0"/&gt;
 *                                         &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" minOccurs="0"/&gt;
 *                                       &lt;/sequence&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CONWQD", propOrder = {
    "bgm",
    "dtm",
    "aut",
    "ftx",
    "segGrp1",
    "segGrp2",
    "segGrp6"
})
public class CONWQD {

    @XmlElement(name = "BGM", required = true)
    protected BGMBeginningOfMessage bgm;
    @XmlElement(name = "DTM")
    protected List<DTMDateTimePeriod> dtm;
    @XmlElement(name = "AUT")
    protected List<AUTAuthenticationResult> aut;
    @XmlElement(name = "FTX")
    protected List<FTXFreeText> ftx;
    @XmlElement(name = "SegGrp-1")
    protected List<CONWQD.SegGrp1> segGrp1;
    @XmlElement(name = "SegGrp-2")
    protected List<CONWQD.SegGrp2> segGrp2;
    @XmlElement(name = "SegGrp-6", required = true)
    protected List<CONWQD.SegGrp6> segGrp6;

    /**
     * Gets the value of the bgm property.
     * 
     * @return
     *     possible object is
     *     {@link BGMBeginningOfMessage }
     *     
     */
    public BGMBeginningOfMessage getBGM() {
        return bgm;
    }

    /**
     * Sets the value of the bgm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BGMBeginningOfMessage }
     *     
     */
    public void setBGM(BGMBeginningOfMessage value) {
        this.bgm = value;
    }

    /**
     * Gets the value of the dtm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the dtm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDTM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DTMDateTimePeriod }
     * 
     * 
     */
    public List<DTMDateTimePeriod> getDTM() {
        if (dtm == null) {
            dtm = new ArrayList<DTMDateTimePeriod>();
        }
        return this.dtm;
    }

    /**
     * Gets the value of the aut property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the aut property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAUT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AUTAuthenticationResult }
     * 
     * 
     */
    public List<AUTAuthenticationResult> getAUT() {
        if (aut == null) {
            aut = new ArrayList<AUTAuthenticationResult>();
        }
        return this.aut;
    }

    /**
     * Gets the value of the ftx property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the ftx property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFTX().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FTXFreeText }
     * 
     * 
     */
    public List<FTXFreeText> getFTX() {
        if (ftx == null) {
            ftx = new ArrayList<FTXFreeText>();
        }
        return this.ftx;
    }

    /**
     * Gets the value of the segGrp1 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the segGrp1 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegGrp1().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CONWQD.SegGrp1 }
     * 
     * 
     */
    public List<CONWQD.SegGrp1> getSegGrp1() {
        if (segGrp1 == null) {
            segGrp1 = new ArrayList<CONWQD.SegGrp1>();
        }
        return this.segGrp1;
    }

    /**
     * Gets the value of the segGrp2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the segGrp2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegGrp2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CONWQD.SegGrp2 }
     * 
     * 
     */
    public List<CONWQD.SegGrp2> getSegGrp2() {
        if (segGrp2 == null) {
            segGrp2 = new ArrayList<CONWQD.SegGrp2>();
        }
        return this.segGrp2;
    }

    /**
     * Gets the value of the segGrp6 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the segGrp6 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegGrp6().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CONWQD.SegGrp6 }
     * 
     * 
     */
    public List<CONWQD.SegGrp6> getSegGrp6() {
        if (segGrp6 == null) {
            segGrp6 = new ArrayList<CONWQD.SegGrp6>();
        }
        return this.segGrp6;
    }

    public CONWQD withBGM(BGMBeginningOfMessage value) {
        setBGM(value);
        return this;
    }

    public CONWQD withDTM(DTMDateTimePeriod... values) {
        if (values!= null) {
            for (DTMDateTimePeriod value: values) {
                getDTM().add(value);
            }
        }
        return this;
    }

    public CONWQD withDTM(Collection<DTMDateTimePeriod> values) {
        if (values!= null) {
            getDTM().addAll(values);
        }
        return this;
    }

    public CONWQD withAUT(AUTAuthenticationResult... values) {
        if (values!= null) {
            for (AUTAuthenticationResult value: values) {
                getAUT().add(value);
            }
        }
        return this;
    }

    public CONWQD withAUT(Collection<AUTAuthenticationResult> values) {
        if (values!= null) {
            getAUT().addAll(values);
        }
        return this;
    }

    public CONWQD withFTX(FTXFreeText... values) {
        if (values!= null) {
            for (FTXFreeText value: values) {
                getFTX().add(value);
            }
        }
        return this;
    }

    public CONWQD withFTX(Collection<FTXFreeText> values) {
        if (values!= null) {
            getFTX().addAll(values);
        }
        return this;
    }

    public CONWQD withSegGrp1(CONWQD.SegGrp1 ... values) {
        if (values!= null) {
            for (CONWQD.SegGrp1 value: values) {
                getSegGrp1().add(value);
            }
        }
        return this;
    }

    public CONWQD withSegGrp1(Collection<CONWQD.SegGrp1> values) {
        if (values!= null) {
            getSegGrp1().addAll(values);
        }
        return this;
    }

    public CONWQD withSegGrp2(CONWQD.SegGrp2 ... values) {
        if (values!= null) {
            for (CONWQD.SegGrp2 value: values) {
                getSegGrp2().add(value);
            }
        }
        return this;
    }

    public CONWQD withSegGrp2(Collection<CONWQD.SegGrp2> values) {
        if (values!= null) {
            getSegGrp2().addAll(values);
        }
        return this;
    }

    public CONWQD withSegGrp6(CONWQD.SegGrp6 ... values) {
        if (values!= null) {
            for (CONWQD.SegGrp6 value: values) {
                getSegGrp6().add(value);
            }
        }
        return this;
    }

    public CONWQD withSegGrp6(Collection<CONWQD.SegGrp6> values) {
        if (values!= null) {
            getSegGrp6().addAll(values);
        }
        return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference"/&gt;
     *           &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="5" minOccurs="0"/&gt;
     *         &lt;/sequence&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rff",
        "dtm"
    })
    public static class SegGrp1 {

        @XmlElement(name = "RFF", required = true)
        protected RFFReference rff;
        @XmlElement(name = "DTM")
        protected List<DTMDateTimePeriod> dtm;

        /**
         * Gets the value of the rff property.
         * 
         * @return
         *     possible object is
         *     {@link RFFReference }
         *     
         */
        public RFFReference getRFF() {
            return rff;
        }

        /**
         * Sets the value of the rff property.
         * 
         * @param value
         *     allowed object is
         *     {@link RFFReference }
         *     
         */
        public void setRFF(RFFReference value) {
            this.rff = value;
        }

        /**
         * Gets the value of the dtm property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the dtm property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDTM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DTMDateTimePeriod }
         * 
         * 
         */
        public List<DTMDateTimePeriod> getDTM() {
            if (dtm == null) {
                dtm = new ArrayList<DTMDateTimePeriod>();
            }
            return this.dtm;
        }

        public CONWQD.SegGrp1 withRFF(RFFReference value) {
            setRFF(value);
            return this;
        }

        public CONWQD.SegGrp1 withDTM(DTMDateTimePeriod... values) {
            if (values!= null) {
                for (DTMDateTimePeriod value: values) {
                    getDTM().add(value);
                }
            }
            return this;
        }

        public CONWQD.SegGrp1 withDTM(Collection<DTMDateTimePeriod> values) {
            if (values!= null) {
                getDTM().addAll(values);
            }
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="NAD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}NAD-NameAndAddress"/&gt;
     *           &lt;element name="LOC" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LOC-PlaceLocationIdentification" maxOccurs="99" minOccurs="0"/&gt;
     *           &lt;element name="FII" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FII-FinancialInstitutionInformation" maxOccurs="5" minOccurs="0"/&gt;
     *         &lt;/sequence&gt;
     *         &lt;element name="SegGrp-3" maxOccurs="10" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference"/&gt;
     *                     &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="5" minOccurs="0"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="SegGrp-4" maxOccurs="5" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="DOC" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DOC-DocumentMessageDetails"/&gt;
     *                     &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="5" minOccurs="0"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="SegGrp-5" maxOccurs="5" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="CTA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}CTA-ContactInformation"/&gt;
     *                     &lt;element name="COM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}COM-CommunicationContact" maxOccurs="5" minOccurs="0"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nad",
        "loc",
        "fii",
        "segGrp3",
        "segGrp4",
        "segGrp5"
    })
    public static class SegGrp2 {

        @XmlElement(name = "NAD", required = true)
        protected NADNameAndAddress nad;
        @XmlElement(name = "LOC")
        protected List<LOCPlaceLocationIdentification> loc;
        @XmlElement(name = "FII")
        protected List<FIIFinancialInstitutionInformation> fii;
        @XmlElement(name = "SegGrp-3")
        protected List<CONWQD.SegGrp2 .SegGrp3> segGrp3;
        @XmlElement(name = "SegGrp-4")
        protected List<CONWQD.SegGrp2 .SegGrp4> segGrp4;
        @XmlElement(name = "SegGrp-5")
        protected List<CONWQD.SegGrp2 .SegGrp5> segGrp5;

        /**
         * Gets the value of the nad property.
         * 
         * @return
         *     possible object is
         *     {@link NADNameAndAddress }
         *     
         */
        public NADNameAndAddress getNAD() {
            return nad;
        }

        /**
         * Sets the value of the nad property.
         * 
         * @param value
         *     allowed object is
         *     {@link NADNameAndAddress }
         *     
         */
        public void setNAD(NADNameAndAddress value) {
            this.nad = value;
        }

        /**
         * Gets the value of the loc property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the loc property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLOC().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LOCPlaceLocationIdentification }
         * 
         * 
         */
        public List<LOCPlaceLocationIdentification> getLOC() {
            if (loc == null) {
                loc = new ArrayList<LOCPlaceLocationIdentification>();
            }
            return this.loc;
        }

        /**
         * Gets the value of the fii property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the fii property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFII().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FIIFinancialInstitutionInformation }
         * 
         * 
         */
        public List<FIIFinancialInstitutionInformation> getFII() {
            if (fii == null) {
                fii = new ArrayList<FIIFinancialInstitutionInformation>();
            }
            return this.fii;
        }

        /**
         * Gets the value of the segGrp3 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the segGrp3 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegGrp3().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CONWQD.SegGrp2 .SegGrp3 }
         * 
         * 
         */
        public List<CONWQD.SegGrp2 .SegGrp3> getSegGrp3() {
            if (segGrp3 == null) {
                segGrp3 = new ArrayList<CONWQD.SegGrp2 .SegGrp3>();
            }
            return this.segGrp3;
        }

        /**
         * Gets the value of the segGrp4 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the segGrp4 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegGrp4().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CONWQD.SegGrp2 .SegGrp4 }
         * 
         * 
         */
        public List<CONWQD.SegGrp2 .SegGrp4> getSegGrp4() {
            if (segGrp4 == null) {
                segGrp4 = new ArrayList<CONWQD.SegGrp2 .SegGrp4>();
            }
            return this.segGrp4;
        }

        /**
         * Gets the value of the segGrp5 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the segGrp5 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegGrp5().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CONWQD.SegGrp2 .SegGrp5 }
         * 
         * 
         */
        public List<CONWQD.SegGrp2 .SegGrp5> getSegGrp5() {
            if (segGrp5 == null) {
                segGrp5 = new ArrayList<CONWQD.SegGrp2 .SegGrp5>();
            }
            return this.segGrp5;
        }

        public CONWQD.SegGrp2 withNAD(NADNameAndAddress value) {
            setNAD(value);
            return this;
        }

        public CONWQD.SegGrp2 withLOC(LOCPlaceLocationIdentification... values) {
            if (values!= null) {
                for (LOCPlaceLocationIdentification value: values) {
                    getLOC().add(value);
                }
            }
            return this;
        }

        public CONWQD.SegGrp2 withLOC(Collection<LOCPlaceLocationIdentification> values) {
            if (values!= null) {
                getLOC().addAll(values);
            }
            return this;
        }

        public CONWQD.SegGrp2 withFII(FIIFinancialInstitutionInformation... values) {
            if (values!= null) {
                for (FIIFinancialInstitutionInformation value: values) {
                    getFII().add(value);
                }
            }
            return this;
        }

        public CONWQD.SegGrp2 withFII(Collection<FIIFinancialInstitutionInformation> values) {
            if (values!= null) {
                getFII().addAll(values);
            }
            return this;
        }

        public CONWQD.SegGrp2 withSegGrp3(CONWQD.SegGrp2 .SegGrp3 ... values) {
            if (values!= null) {
                for (CONWQD.SegGrp2 .SegGrp3 value: values) {
                    getSegGrp3().add(value);
                }
            }
            return this;
        }

        public CONWQD.SegGrp2 withSegGrp3(Collection<CONWQD.SegGrp2 .SegGrp3> values) {
            if (values!= null) {
                getSegGrp3().addAll(values);
            }
            return this;
        }

        public CONWQD.SegGrp2 withSegGrp4(CONWQD.SegGrp2 .SegGrp4 ... values) {
            if (values!= null) {
                for (CONWQD.SegGrp2 .SegGrp4 value: values) {
                    getSegGrp4().add(value);
                }
            }
            return this;
        }

        public CONWQD.SegGrp2 withSegGrp4(Collection<CONWQD.SegGrp2 .SegGrp4> values) {
            if (values!= null) {
                getSegGrp4().addAll(values);
            }
            return this;
        }

        public CONWQD.SegGrp2 withSegGrp5(CONWQD.SegGrp2 .SegGrp5 ... values) {
            if (values!= null) {
                for (CONWQD.SegGrp2 .SegGrp5 value: values) {
                    getSegGrp5().add(value);
                }
            }
            return this;
        }

        public CONWQD.SegGrp2 withSegGrp5(Collection<CONWQD.SegGrp2 .SegGrp5> values) {
            if (values!= null) {
                getSegGrp5().addAll(values);
            }
            return this;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference"/&gt;
         *           &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="5" minOccurs="0"/&gt;
         *         &lt;/sequence&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rff",
            "dtm"
        })
        public static class SegGrp3 {

            @XmlElement(name = "RFF", required = true)
            protected RFFReference rff;
            @XmlElement(name = "DTM")
            protected List<DTMDateTimePeriod> dtm;

            /**
             * Gets the value of the rff property.
             * 
             * @return
             *     possible object is
             *     {@link RFFReference }
             *     
             */
            public RFFReference getRFF() {
                return rff;
            }

            /**
             * Sets the value of the rff property.
             * 
             * @param value
             *     allowed object is
             *     {@link RFFReference }
             *     
             */
            public void setRFF(RFFReference value) {
                this.rff = value;
            }

            /**
             * Gets the value of the dtm property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the dtm property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDTM().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DTMDateTimePeriod }
             * 
             * 
             */
            public List<DTMDateTimePeriod> getDTM() {
                if (dtm == null) {
                    dtm = new ArrayList<DTMDateTimePeriod>();
                }
                return this.dtm;
            }

            public CONWQD.SegGrp2 .SegGrp3 withRFF(RFFReference value) {
                setRFF(value);
                return this;
            }

            public CONWQD.SegGrp2 .SegGrp3 withDTM(DTMDateTimePeriod... values) {
                if (values!= null) {
                    for (DTMDateTimePeriod value: values) {
                        getDTM().add(value);
                    }
                }
                return this;
            }

            public CONWQD.SegGrp2 .SegGrp3 withDTM(Collection<DTMDateTimePeriod> values) {
                if (values!= null) {
                    getDTM().addAll(values);
                }
                return this;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="DOC" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DOC-DocumentMessageDetails"/&gt;
         *           &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="5" minOccurs="0"/&gt;
         *         &lt;/sequence&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "doc",
            "dtm"
        })
        public static class SegGrp4 {

            @XmlElement(name = "DOC", required = true)
            protected DOCDocumentMessageDetails doc;
            @XmlElement(name = "DTM")
            protected List<DTMDateTimePeriod> dtm;

            /**
             * Gets the value of the doc property.
             * 
             * @return
             *     possible object is
             *     {@link DOCDocumentMessageDetails }
             *     
             */
            public DOCDocumentMessageDetails getDOC() {
                return doc;
            }

            /**
             * Sets the value of the doc property.
             * 
             * @param value
             *     allowed object is
             *     {@link DOCDocumentMessageDetails }
             *     
             */
            public void setDOC(DOCDocumentMessageDetails value) {
                this.doc = value;
            }

            /**
             * Gets the value of the dtm property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the dtm property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDTM().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DTMDateTimePeriod }
             * 
             * 
             */
            public List<DTMDateTimePeriod> getDTM() {
                if (dtm == null) {
                    dtm = new ArrayList<DTMDateTimePeriod>();
                }
                return this.dtm;
            }

            public CONWQD.SegGrp2 .SegGrp4 withDOC(DOCDocumentMessageDetails value) {
                setDOC(value);
                return this;
            }

            public CONWQD.SegGrp2 .SegGrp4 withDTM(DTMDateTimePeriod... values) {
                if (values!= null) {
                    for (DTMDateTimePeriod value: values) {
                        getDTM().add(value);
                    }
                }
                return this;
            }

            public CONWQD.SegGrp2 .SegGrp4 withDTM(Collection<DTMDateTimePeriod> values) {
                if (values!= null) {
                    getDTM().addAll(values);
                }
                return this;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="CTA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}CTA-ContactInformation"/&gt;
         *           &lt;element name="COM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}COM-CommunicationContact" maxOccurs="5" minOccurs="0"/&gt;
         *         &lt;/sequence&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cta",
            "com"
        })
        public static class SegGrp5 {

            @XmlElement(name = "CTA", required = true)
            protected CTAContactInformation cta;
            @XmlElement(name = "COM")
            protected List<COMCommunicationContact> com;

            /**
             * Gets the value of the cta property.
             * 
             * @return
             *     possible object is
             *     {@link CTAContactInformation }
             *     
             */
            public CTAContactInformation getCTA() {
                return cta;
            }

            /**
             * Sets the value of the cta property.
             * 
             * @param value
             *     allowed object is
             *     {@link CTAContactInformation }
             *     
             */
            public void setCTA(CTAContactInformation value) {
                this.cta = value;
            }

            /**
             * Gets the value of the com property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the com property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCOM().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link COMCommunicationContact }
             * 
             * 
             */
            public List<COMCommunicationContact> getCOM() {
                if (com == null) {
                    com = new ArrayList<COMCommunicationContact>();
                }
                return this.com;
            }

            public CONWQD.SegGrp2 .SegGrp5 withCTA(CTAContactInformation value) {
                setCTA(value);
                return this;
            }

            public CONWQD.SegGrp2 .SegGrp5 withCOM(COMCommunicationContact... values) {
                if (values!= null) {
                    for (COMCommunicationContact value: values) {
                        getCOM().add(value);
                    }
                }
                return this;
            }

            public CONWQD.SegGrp2 .SegGrp5 withCOM(Collection<COMCommunicationContact> values) {
                if (values!= null) {
                    getCOM().addAll(values);
                }
                return this;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="BII" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}BII-StructureIdentification"/&gt;
     *           &lt;element name="QTY" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}QTY-Quantity" maxOccurs="3" minOccurs="0"/&gt;
     *         &lt;/sequence&gt;
     *         &lt;element name="SegGrp-7" maxOccurs="99" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference"/&gt;
     *                     &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" minOccurs="0"/&gt;
     *                     &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" minOccurs="0"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="SegGrp-8" maxOccurs="999" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="LIN" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LIN-LineItem"/&gt;
     *                     &lt;element name="GEI" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}GEI-ProcessingInformation"/&gt;
     *                     &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" minOccurs="0"/&gt;
     *                   &lt;/sequence&gt;
     *                   &lt;element name="SegGrp-9" maxOccurs="10" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;sequence&gt;
     *                               &lt;element name="QTY" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}QTY-Quantity"/&gt;
     *                               &lt;element name="GEI" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}GEI-ProcessingInformation" minOccurs="0"/&gt;
     *                               &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference" minOccurs="0"/&gt;
     *                               &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" minOccurs="0"/&gt;
     *                             &lt;/sequence&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bii",
        "qty",
        "segGrp7",
        "segGrp8"
    })
    public static class SegGrp6 {

        @XmlElement(name = "BII", required = true)
        protected BIIStructureIdentification bii;
        @XmlElement(name = "QTY")
        protected List<QTYQuantity> qty;
        @XmlElement(name = "SegGrp-7")
        protected List<CONWQD.SegGrp6 .SegGrp7> segGrp7;
        @XmlElement(name = "SegGrp-8")
        protected List<CONWQD.SegGrp6 .SegGrp8> segGrp8;

        /**
         * Gets the value of the bii property.
         * 
         * @return
         *     possible object is
         *     {@link BIIStructureIdentification }
         *     
         */
        public BIIStructureIdentification getBII() {
            return bii;
        }

        /**
         * Sets the value of the bii property.
         * 
         * @param value
         *     allowed object is
         *     {@link BIIStructureIdentification }
         *     
         */
        public void setBII(BIIStructureIdentification value) {
            this.bii = value;
        }

        /**
         * Gets the value of the qty property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the qty property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getQTY().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link QTYQuantity }
         * 
         * 
         */
        public List<QTYQuantity> getQTY() {
            if (qty == null) {
                qty = new ArrayList<QTYQuantity>();
            }
            return this.qty;
        }

        /**
         * Gets the value of the segGrp7 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the segGrp7 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegGrp7().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CONWQD.SegGrp6 .SegGrp7 }
         * 
         * 
         */
        public List<CONWQD.SegGrp6 .SegGrp7> getSegGrp7() {
            if (segGrp7 == null) {
                segGrp7 = new ArrayList<CONWQD.SegGrp6 .SegGrp7>();
            }
            return this.segGrp7;
        }

        /**
         * Gets the value of the segGrp8 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the segGrp8 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegGrp8().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CONWQD.SegGrp6 .SegGrp8 }
         * 
         * 
         */
        public List<CONWQD.SegGrp6 .SegGrp8> getSegGrp8() {
            if (segGrp8 == null) {
                segGrp8 = new ArrayList<CONWQD.SegGrp6 .SegGrp8>();
            }
            return this.segGrp8;
        }

        public CONWQD.SegGrp6 withBII(BIIStructureIdentification value) {
            setBII(value);
            return this;
        }

        public CONWQD.SegGrp6 withQTY(QTYQuantity... values) {
            if (values!= null) {
                for (QTYQuantity value: values) {
                    getQTY().add(value);
                }
            }
            return this;
        }

        public CONWQD.SegGrp6 withQTY(Collection<QTYQuantity> values) {
            if (values!= null) {
                getQTY().addAll(values);
            }
            return this;
        }

        public CONWQD.SegGrp6 withSegGrp7(CONWQD.SegGrp6 .SegGrp7 ... values) {
            if (values!= null) {
                for (CONWQD.SegGrp6 .SegGrp7 value: values) {
                    getSegGrp7().add(value);
                }
            }
            return this;
        }

        public CONWQD.SegGrp6 withSegGrp7(Collection<CONWQD.SegGrp6 .SegGrp7> values) {
            if (values!= null) {
                getSegGrp7().addAll(values);
            }
            return this;
        }

        public CONWQD.SegGrp6 withSegGrp8(CONWQD.SegGrp6 .SegGrp8 ... values) {
            if (values!= null) {
                for (CONWQD.SegGrp6 .SegGrp8 value: values) {
                    getSegGrp8().add(value);
                }
            }
            return this;
        }

        public CONWQD.SegGrp6 withSegGrp8(Collection<CONWQD.SegGrp6 .SegGrp8> values) {
            if (values!= null) {
                getSegGrp8().addAll(values);
            }
            return this;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference"/&gt;
         *           &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" minOccurs="0"/&gt;
         *           &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" minOccurs="0"/&gt;
         *         &lt;/sequence&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rff",
            "ftx",
            "dtm"
        })
        public static class SegGrp7 {

            @XmlElement(name = "RFF", required = true)
            protected RFFReference rff;
            @XmlElement(name = "FTX")
            protected FTXFreeText ftx;
            @XmlElement(name = "DTM")
            protected DTMDateTimePeriod dtm;

            /**
             * Gets the value of the rff property.
             * 
             * @return
             *     possible object is
             *     {@link RFFReference }
             *     
             */
            public RFFReference getRFF() {
                return rff;
            }

            /**
             * Sets the value of the rff property.
             * 
             * @param value
             *     allowed object is
             *     {@link RFFReference }
             *     
             */
            public void setRFF(RFFReference value) {
                this.rff = value;
            }

            /**
             * Gets the value of the ftx property.
             * 
             * @return
             *     possible object is
             *     {@link FTXFreeText }
             *     
             */
            public FTXFreeText getFTX() {
                return ftx;
            }

            /**
             * Sets the value of the ftx property.
             * 
             * @param value
             *     allowed object is
             *     {@link FTXFreeText }
             *     
             */
            public void setFTX(FTXFreeText value) {
                this.ftx = value;
            }

            /**
             * Gets the value of the dtm property.
             * 
             * @return
             *     possible object is
             *     {@link DTMDateTimePeriod }
             *     
             */
            public DTMDateTimePeriod getDTM() {
                return dtm;
            }

            /**
             * Sets the value of the dtm property.
             * 
             * @param value
             *     allowed object is
             *     {@link DTMDateTimePeriod }
             *     
             */
            public void setDTM(DTMDateTimePeriod value) {
                this.dtm = value;
            }

            public CONWQD.SegGrp6 .SegGrp7 withRFF(RFFReference value) {
                setRFF(value);
                return this;
            }

            public CONWQD.SegGrp6 .SegGrp7 withFTX(FTXFreeText value) {
                setFTX(value);
                return this;
            }

            public CONWQD.SegGrp6 .SegGrp7 withDTM(DTMDateTimePeriod value) {
                setDTM(value);
                return this;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="LIN" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LIN-LineItem"/&gt;
         *           &lt;element name="GEI" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}GEI-ProcessingInformation"/&gt;
         *           &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" minOccurs="0"/&gt;
         *         &lt;/sequence&gt;
         *         &lt;element name="SegGrp-9" maxOccurs="10" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;sequence&gt;
         *                     &lt;element name="QTY" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}QTY-Quantity"/&gt;
         *                     &lt;element name="GEI" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}GEI-ProcessingInformation" minOccurs="0"/&gt;
         *                     &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference" minOccurs="0"/&gt;
         *                     &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" minOccurs="0"/&gt;
         *                   &lt;/sequence&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lin",
            "gei",
            "ftx",
            "segGrp9"
        })
        public static class SegGrp8 {

            @XmlElement(name = "LIN", required = true)
            protected LINLineItem lin;
            @XmlElement(name = "GEI", required = true)
            protected GEIProcessingInformation gei;
            @XmlElement(name = "FTX")
            protected FTXFreeText ftx;
            @XmlElement(name = "SegGrp-9")
            protected List<CONWQD.SegGrp6 .SegGrp8 .SegGrp9> segGrp9;

            /**
             * Gets the value of the lin property.
             * 
             * @return
             *     possible object is
             *     {@link LINLineItem }
             *     
             */
            public LINLineItem getLIN() {
                return lin;
            }

            /**
             * Sets the value of the lin property.
             * 
             * @param value
             *     allowed object is
             *     {@link LINLineItem }
             *     
             */
            public void setLIN(LINLineItem value) {
                this.lin = value;
            }

            /**
             * Gets the value of the gei property.
             * 
             * @return
             *     possible object is
             *     {@link GEIProcessingInformation }
             *     
             */
            public GEIProcessingInformation getGEI() {
                return gei;
            }

            /**
             * Sets the value of the gei property.
             * 
             * @param value
             *     allowed object is
             *     {@link GEIProcessingInformation }
             *     
             */
            public void setGEI(GEIProcessingInformation value) {
                this.gei = value;
            }

            /**
             * Gets the value of the ftx property.
             * 
             * @return
             *     possible object is
             *     {@link FTXFreeText }
             *     
             */
            public FTXFreeText getFTX() {
                return ftx;
            }

            /**
             * Sets the value of the ftx property.
             * 
             * @param value
             *     allowed object is
             *     {@link FTXFreeText }
             *     
             */
            public void setFTX(FTXFreeText value) {
                this.ftx = value;
            }

            /**
             * Gets the value of the segGrp9 property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the segGrp9 property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSegGrp9().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link CONWQD.SegGrp6 .SegGrp8 .SegGrp9 }
             * 
             * 
             */
            public List<CONWQD.SegGrp6 .SegGrp8 .SegGrp9> getSegGrp9() {
                if (segGrp9 == null) {
                    segGrp9 = new ArrayList<CONWQD.SegGrp6 .SegGrp8 .SegGrp9>();
                }
                return this.segGrp9;
            }

            public CONWQD.SegGrp6 .SegGrp8 withLIN(LINLineItem value) {
                setLIN(value);
                return this;
            }

            public CONWQD.SegGrp6 .SegGrp8 withGEI(GEIProcessingInformation value) {
                setGEI(value);
                return this;
            }

            public CONWQD.SegGrp6 .SegGrp8 withFTX(FTXFreeText value) {
                setFTX(value);
                return this;
            }

            public CONWQD.SegGrp6 .SegGrp8 withSegGrp9(CONWQD.SegGrp6 .SegGrp8 .SegGrp9 ... values) {
                if (values!= null) {
                    for (CONWQD.SegGrp6 .SegGrp8 .SegGrp9 value: values) {
                        getSegGrp9().add(value);
                    }
                }
                return this;
            }

            public CONWQD.SegGrp6 .SegGrp8 withSegGrp9(Collection<CONWQD.SegGrp6 .SegGrp8 .SegGrp9> values) {
                if (values!= null) {
                    getSegGrp9().addAll(values);
                }
                return this;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;sequence&gt;
             *           &lt;element name="QTY" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}QTY-Quantity"/&gt;
             *           &lt;element name="GEI" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}GEI-ProcessingInformation" minOccurs="0"/&gt;
             *           &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference" minOccurs="0"/&gt;
             *           &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" minOccurs="0"/&gt;
             *         &lt;/sequence&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "qty",
                "gei",
                "rff",
                "ftx"
            })
            public static class SegGrp9 {

                @XmlElement(name = "QTY", required = true)
                protected QTYQuantity qty;
                @XmlElement(name = "GEI")
                protected GEIProcessingInformation gei;
                @XmlElement(name = "RFF")
                protected RFFReference rff;
                @XmlElement(name = "FTX")
                protected FTXFreeText ftx;

                /**
                 * Gets the value of the qty property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link QTYQuantity }
                 *     
                 */
                public QTYQuantity getQTY() {
                    return qty;
                }

                /**
                 * Sets the value of the qty property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link QTYQuantity }
                 *     
                 */
                public void setQTY(QTYQuantity value) {
                    this.qty = value;
                }

                /**
                 * Gets the value of the gei property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GEIProcessingInformation }
                 *     
                 */
                public GEIProcessingInformation getGEI() {
                    return gei;
                }

                /**
                 * Sets the value of the gei property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GEIProcessingInformation }
                 *     
                 */
                public void setGEI(GEIProcessingInformation value) {
                    this.gei = value;
                }

                /**
                 * Gets the value of the rff property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link RFFReference }
                 *     
                 */
                public RFFReference getRFF() {
                    return rff;
                }

                /**
                 * Sets the value of the rff property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link RFFReference }
                 *     
                 */
                public void setRFF(RFFReference value) {
                    this.rff = value;
                }

                /**
                 * Gets the value of the ftx property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link FTXFreeText }
                 *     
                 */
                public FTXFreeText getFTX() {
                    return ftx;
                }

                /**
                 * Sets the value of the ftx property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link FTXFreeText }
                 *     
                 */
                public void setFTX(FTXFreeText value) {
                    this.ftx = value;
                }

                public CONWQD.SegGrp6 .SegGrp8 .SegGrp9 withQTY(QTYQuantity value) {
                    setQTY(value);
                    return this;
                }

                public CONWQD.SegGrp6 .SegGrp8 .SegGrp9 withGEI(GEIProcessingInformation value) {
                    setGEI(value);
                    return this;
                }

                public CONWQD.SegGrp6 .SegGrp8 .SegGrp9 withRFF(RFFReference value) {
                    setRFF(value);
                    return this;
                }

                public CONWQD.SegGrp6 .SegGrp8 .SegGrp9 withFTX(FTXFreeText value) {
                    setFTX(value);
                    return this;
                }

            }

        }

    }

}
