/*-
 * ========================LICENSE_START=================================
 * d16b-edifact-binding
 * %%
 * Copyright (C) 2020 - 2024 Smooks
 * %%
 * Licensed under the terms of the Apache License Version 2.0, or
 * the GNU Lesser General Public License version 3.0 or later.
 * 
 * SPDX-License-Identifier: Apache-2.0 OR LGPL-3.0-or-later
 * 
 * ======================================================================
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * ======================================================================
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * =========================LICENSE_END==================================
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.17 at 06:20:44 PM UTC 
//


package org.smooks.edifact.binding.d16b;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.smooks.edifact.binding.service.UNSSectionControl;


/**
 * <p>Java class for DESTIM complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DESTIM"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="BGM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}BGM-BeginningOfMessage"/&gt;
 *           &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="9"/&gt;
 *           &lt;element name="GEI" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}GEI-ProcessingInformation" minOccurs="0"/&gt;
 *           &lt;element name="CUX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}CUX-Currencies" maxOccurs="9" minOccurs="0"/&gt;
 *           &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference" maxOccurs="9" minOccurs="0"/&gt;
 *           &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" maxOccurs="9" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="SegGrp-1"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="EQD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}EQD-EquipmentDetails"/&gt;
 *                     &lt;element name="DIM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DIM-Dimensions" minOccurs="0"/&gt;
 *                     &lt;element name="IMD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}IMD-ItemDescription" maxOccurs="9" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SegGrp-2" maxOccurs="9" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="NAD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}NAD-NameAndAddress"/&gt;
 *                     &lt;element name="MOA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MOA-MonetaryAmount" maxOccurs="9" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;element name="SegGrp-3" maxOccurs="9" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="CTA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}CTA-ContactInformation"/&gt;
 *                               &lt;element name="COM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}COM-CommunicationContact" maxOccurs="9" minOccurs="0"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SegGrp-4" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="TDT" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}TDT-TransportInformation"/&gt;
 *                     &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="9" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;element name="SegGrp-5" maxOccurs="9" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="LOC" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LOC-PlaceLocationIdentification"/&gt;
 *                               &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="9" minOccurs="0"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="UNS" type="{http://www.ibm.com/dfdl/edi/un/service/4.1}UNS-SectionControl"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;element name="SegGrp-6" maxOccurs="9" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod"/&gt;
 *                     &lt;element name="LOC" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LOC-PlaceLocationIdentification" minOccurs="0"/&gt;
 *                     &lt;element name="NAD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}NAD-NameAndAddress" maxOccurs="9" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SegGrp-7" maxOccurs="9" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference"/&gt;
 *                     &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" minOccurs="0"/&gt;
 *                     &lt;element name="NAD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}NAD-NameAndAddress" maxOccurs="9" minOccurs="0"/&gt;
 *                     &lt;element name="MOA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MOA-MonetaryAmount" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SegGrp-8" maxOccurs="999" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="LIN" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LIN-LineItem"/&gt;
 *                     &lt;element name="DIM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DIM-Dimensions" minOccurs="0"/&gt;
 *                     &lt;element name="QTY" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}QTY-Quantity" minOccurs="0"/&gt;
 *                     &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" maxOccurs="9" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;element name="SegGrp-9" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="DAM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DAM-Damage"/&gt;
 *                               &lt;element name="COD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}COD-ComponentDetails" minOccurs="0"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="SegGrp-10" maxOccurs="9" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="RTE" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RTE-RateDetails"/&gt;
 *                               &lt;element name="QTY" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}QTY-Quantity"/&gt;
 *                             &lt;/sequence&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="SegGrp-11" maxOccurs="9" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;sequence&gt;
 *                               &lt;element name="NAD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}NAD-NameAndAddress"/&gt;
 *                             &lt;/sequence&gt;
 *                             &lt;element name="SegGrp-12" maxOccurs="9"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;sequence&gt;
 *                                         &lt;element name="MOA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MOA-MonetaryAmount"/&gt;
 *                                         &lt;element name="TAX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}TAX-DutyTaxFeeDetails" minOccurs="0"/&gt;
 *                                         &lt;element name="MEA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MEA-Measurements" minOccurs="0"/&gt;
 *                                       &lt;/sequence&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="CNT" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}CNT-ControlTotal" maxOccurs="9" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DESTIM", propOrder = {
    "bgm",
    "dtm",
    "gei",
    "cux",
    "rff",
    "ftx",
    "segGrp1",
    "segGrp2",
    "segGrp4",
    "uns",
    "segGrp6",
    "segGrp7",
    "segGrp8",
    "cnt"
})
public class DESTIM {

    @XmlElement(name = "BGM", required = true)
    protected BGMBeginningOfMessage bgm;
    @XmlElement(name = "DTM", required = true)
    protected List<DTMDateTimePeriod> dtm;
    @XmlElement(name = "GEI")
    protected GEIProcessingInformation gei;
    @XmlElement(name = "CUX")
    protected List<CUXCurrencies> cux;
    @XmlElement(name = "RFF")
    protected List<RFFReference> rff;
    @XmlElement(name = "FTX")
    protected List<FTXFreeText> ftx;
    @XmlElement(name = "SegGrp-1", required = true)
    protected DESTIM.SegGrp1 segGrp1;
    @XmlElement(name = "SegGrp-2")
    protected List<DESTIM.SegGrp2> segGrp2;
    @XmlElement(name = "SegGrp-4")
    protected DESTIM.SegGrp4 segGrp4;
    @XmlElement(name = "UNS", required = true)
    protected UNSSectionControl uns;
    @XmlElement(name = "SegGrp-6")
    protected List<DESTIM.SegGrp6> segGrp6;
    @XmlElement(name = "SegGrp-7")
    protected List<DESTIM.SegGrp7> segGrp7;
    @XmlElement(name = "SegGrp-8")
    protected List<DESTIM.SegGrp8> segGrp8;
    @XmlElement(name = "CNT")
    protected List<CNTControlTotal> cnt;

    /**
     * Gets the value of the bgm property.
     * 
     * @return
     *     possible object is
     *     {@link BGMBeginningOfMessage }
     *     
     */
    public BGMBeginningOfMessage getBGM() {
        return bgm;
    }

    /**
     * Sets the value of the bgm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BGMBeginningOfMessage }
     *     
     */
    public void setBGM(BGMBeginningOfMessage value) {
        this.bgm = value;
    }

    /**
     * Gets the value of the dtm property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the dtm property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDTM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DTMDateTimePeriod }
     * 
     * 
     */
    public List<DTMDateTimePeriod> getDTM() {
        if (dtm == null) {
            dtm = new ArrayList<DTMDateTimePeriod>();
        }
        return this.dtm;
    }

    /**
     * Gets the value of the gei property.
     * 
     * @return
     *     possible object is
     *     {@link GEIProcessingInformation }
     *     
     */
    public GEIProcessingInformation getGEI() {
        return gei;
    }

    /**
     * Sets the value of the gei property.
     * 
     * @param value
     *     allowed object is
     *     {@link GEIProcessingInformation }
     *     
     */
    public void setGEI(GEIProcessingInformation value) {
        this.gei = value;
    }

    /**
     * Gets the value of the cux property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the cux property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCUX().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CUXCurrencies }
     * 
     * 
     */
    public List<CUXCurrencies> getCUX() {
        if (cux == null) {
            cux = new ArrayList<CUXCurrencies>();
        }
        return this.cux;
    }

    /**
     * Gets the value of the rff property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the rff property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRFF().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RFFReference }
     * 
     * 
     */
    public List<RFFReference> getRFF() {
        if (rff == null) {
            rff = new ArrayList<RFFReference>();
        }
        return this.rff;
    }

    /**
     * Gets the value of the ftx property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the ftx property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFTX().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FTXFreeText }
     * 
     * 
     */
    public List<FTXFreeText> getFTX() {
        if (ftx == null) {
            ftx = new ArrayList<FTXFreeText>();
        }
        return this.ftx;
    }

    /**
     * Gets the value of the segGrp1 property.
     * 
     * @return
     *     possible object is
     *     {@link DESTIM.SegGrp1 }
     *     
     */
    public DESTIM.SegGrp1 getSegGrp1() {
        return segGrp1;
    }

    /**
     * Sets the value of the segGrp1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DESTIM.SegGrp1 }
     *     
     */
    public void setSegGrp1(DESTIM.SegGrp1 value) {
        this.segGrp1 = value;
    }

    /**
     * Gets the value of the segGrp2 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the segGrp2 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegGrp2().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DESTIM.SegGrp2 }
     * 
     * 
     */
    public List<DESTIM.SegGrp2> getSegGrp2() {
        if (segGrp2 == null) {
            segGrp2 = new ArrayList<DESTIM.SegGrp2>();
        }
        return this.segGrp2;
    }

    /**
     * Gets the value of the segGrp4 property.
     * 
     * @return
     *     possible object is
     *     {@link DESTIM.SegGrp4 }
     *     
     */
    public DESTIM.SegGrp4 getSegGrp4() {
        return segGrp4;
    }

    /**
     * Sets the value of the segGrp4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DESTIM.SegGrp4 }
     *     
     */
    public void setSegGrp4(DESTIM.SegGrp4 value) {
        this.segGrp4 = value;
    }

    /**
     * Gets the value of the uns property.
     * 
     * @return
     *     possible object is
     *     {@link UNSSectionControl }
     *     
     */
    public UNSSectionControl getUNS() {
        return uns;
    }

    /**
     * Sets the value of the uns property.
     * 
     * @param value
     *     allowed object is
     *     {@link UNSSectionControl }
     *     
     */
    public void setUNS(UNSSectionControl value) {
        this.uns = value;
    }

    /**
     * Gets the value of the segGrp6 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the segGrp6 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegGrp6().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DESTIM.SegGrp6 }
     * 
     * 
     */
    public List<DESTIM.SegGrp6> getSegGrp6() {
        if (segGrp6 == null) {
            segGrp6 = new ArrayList<DESTIM.SegGrp6>();
        }
        return this.segGrp6;
    }

    /**
     * Gets the value of the segGrp7 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the segGrp7 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegGrp7().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DESTIM.SegGrp7 }
     * 
     * 
     */
    public List<DESTIM.SegGrp7> getSegGrp7() {
        if (segGrp7 == null) {
            segGrp7 = new ArrayList<DESTIM.SegGrp7>();
        }
        return this.segGrp7;
    }

    /**
     * Gets the value of the segGrp8 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the segGrp8 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSegGrp8().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DESTIM.SegGrp8 }
     * 
     * 
     */
    public List<DESTIM.SegGrp8> getSegGrp8() {
        if (segGrp8 == null) {
            segGrp8 = new ArrayList<DESTIM.SegGrp8>();
        }
        return this.segGrp8;
    }

    /**
     * Gets the value of the cnt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the cnt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCNT().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CNTControlTotal }
     * 
     * 
     */
    public List<CNTControlTotal> getCNT() {
        if (cnt == null) {
            cnt = new ArrayList<CNTControlTotal>();
        }
        return this.cnt;
    }

    public DESTIM withBGM(BGMBeginningOfMessage value) {
        setBGM(value);
        return this;
    }

    public DESTIM withDTM(DTMDateTimePeriod... values) {
        if (values!= null) {
            for (DTMDateTimePeriod value: values) {
                getDTM().add(value);
            }
        }
        return this;
    }

    public DESTIM withDTM(Collection<DTMDateTimePeriod> values) {
        if (values!= null) {
            getDTM().addAll(values);
        }
        return this;
    }

    public DESTIM withGEI(GEIProcessingInformation value) {
        setGEI(value);
        return this;
    }

    public DESTIM withCUX(CUXCurrencies... values) {
        if (values!= null) {
            for (CUXCurrencies value: values) {
                getCUX().add(value);
            }
        }
        return this;
    }

    public DESTIM withCUX(Collection<CUXCurrencies> values) {
        if (values!= null) {
            getCUX().addAll(values);
        }
        return this;
    }

    public DESTIM withRFF(RFFReference... values) {
        if (values!= null) {
            for (RFFReference value: values) {
                getRFF().add(value);
            }
        }
        return this;
    }

    public DESTIM withRFF(Collection<RFFReference> values) {
        if (values!= null) {
            getRFF().addAll(values);
        }
        return this;
    }

    public DESTIM withFTX(FTXFreeText... values) {
        if (values!= null) {
            for (FTXFreeText value: values) {
                getFTX().add(value);
            }
        }
        return this;
    }

    public DESTIM withFTX(Collection<FTXFreeText> values) {
        if (values!= null) {
            getFTX().addAll(values);
        }
        return this;
    }

    public DESTIM withSegGrp1(DESTIM.SegGrp1 value) {
        setSegGrp1(value);
        return this;
    }

    public DESTIM withSegGrp2(DESTIM.SegGrp2 ... values) {
        if (values!= null) {
            for (DESTIM.SegGrp2 value: values) {
                getSegGrp2().add(value);
            }
        }
        return this;
    }

    public DESTIM withSegGrp2(Collection<DESTIM.SegGrp2> values) {
        if (values!= null) {
            getSegGrp2().addAll(values);
        }
        return this;
    }

    public DESTIM withSegGrp4(DESTIM.SegGrp4 value) {
        setSegGrp4(value);
        return this;
    }

    public DESTIM withUNS(UNSSectionControl value) {
        setUNS(value);
        return this;
    }

    public DESTIM withSegGrp6(DESTIM.SegGrp6 ... values) {
        if (values!= null) {
            for (DESTIM.SegGrp6 value: values) {
                getSegGrp6().add(value);
            }
        }
        return this;
    }

    public DESTIM withSegGrp6(Collection<DESTIM.SegGrp6> values) {
        if (values!= null) {
            getSegGrp6().addAll(values);
        }
        return this;
    }

    public DESTIM withSegGrp7(DESTIM.SegGrp7 ... values) {
        if (values!= null) {
            for (DESTIM.SegGrp7 value: values) {
                getSegGrp7().add(value);
            }
        }
        return this;
    }

    public DESTIM withSegGrp7(Collection<DESTIM.SegGrp7> values) {
        if (values!= null) {
            getSegGrp7().addAll(values);
        }
        return this;
    }

    public DESTIM withSegGrp8(DESTIM.SegGrp8 ... values) {
        if (values!= null) {
            for (DESTIM.SegGrp8 value: values) {
                getSegGrp8().add(value);
            }
        }
        return this;
    }

    public DESTIM withSegGrp8(Collection<DESTIM.SegGrp8> values) {
        if (values!= null) {
            getSegGrp8().addAll(values);
        }
        return this;
    }

    public DESTIM withCNT(CNTControlTotal... values) {
        if (values!= null) {
            for (CNTControlTotal value: values) {
                getCNT().add(value);
            }
        }
        return this;
    }

    public DESTIM withCNT(Collection<CNTControlTotal> values) {
        if (values!= null) {
            getCNT().addAll(values);
        }
        return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="EQD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}EQD-EquipmentDetails"/&gt;
     *           &lt;element name="DIM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DIM-Dimensions" minOccurs="0"/&gt;
     *           &lt;element name="IMD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}IMD-ItemDescription" maxOccurs="9" minOccurs="0"/&gt;
     *         &lt;/sequence&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eqd",
        "dim",
        "imd"
    })
    public static class SegGrp1 {

        @XmlElement(name = "EQD", required = true)
        protected EQDEquipmentDetails eqd;
        @XmlElement(name = "DIM")
        protected DIMDimensions dim;
        @XmlElement(name = "IMD")
        protected List<IMDItemDescription> imd;

        /**
         * Gets the value of the eqd property.
         * 
         * @return
         *     possible object is
         *     {@link EQDEquipmentDetails }
         *     
         */
        public EQDEquipmentDetails getEQD() {
            return eqd;
        }

        /**
         * Sets the value of the eqd property.
         * 
         * @param value
         *     allowed object is
         *     {@link EQDEquipmentDetails }
         *     
         */
        public void setEQD(EQDEquipmentDetails value) {
            this.eqd = value;
        }

        /**
         * Gets the value of the dim property.
         * 
         * @return
         *     possible object is
         *     {@link DIMDimensions }
         *     
         */
        public DIMDimensions getDIM() {
            return dim;
        }

        /**
         * Sets the value of the dim property.
         * 
         * @param value
         *     allowed object is
         *     {@link DIMDimensions }
         *     
         */
        public void setDIM(DIMDimensions value) {
            this.dim = value;
        }

        /**
         * Gets the value of the imd property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the imd property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIMD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IMDItemDescription }
         * 
         * 
         */
        public List<IMDItemDescription> getIMD() {
            if (imd == null) {
                imd = new ArrayList<IMDItemDescription>();
            }
            return this.imd;
        }

        public DESTIM.SegGrp1 withEQD(EQDEquipmentDetails value) {
            setEQD(value);
            return this;
        }

        public DESTIM.SegGrp1 withDIM(DIMDimensions value) {
            setDIM(value);
            return this;
        }

        public DESTIM.SegGrp1 withIMD(IMDItemDescription... values) {
            if (values!= null) {
                for (IMDItemDescription value: values) {
                    getIMD().add(value);
                }
            }
            return this;
        }

        public DESTIM.SegGrp1 withIMD(Collection<IMDItemDescription> values) {
            if (values!= null) {
                getIMD().addAll(values);
            }
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="NAD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}NAD-NameAndAddress"/&gt;
     *           &lt;element name="MOA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MOA-MonetaryAmount" maxOccurs="9" minOccurs="0"/&gt;
     *         &lt;/sequence&gt;
     *         &lt;element name="SegGrp-3" maxOccurs="9" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="CTA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}CTA-ContactInformation"/&gt;
     *                     &lt;element name="COM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}COM-CommunicationContact" maxOccurs="9" minOccurs="0"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nad",
        "moa",
        "segGrp3"
    })
    public static class SegGrp2 {

        @XmlElement(name = "NAD", required = true)
        protected NADNameAndAddress nad;
        @XmlElement(name = "MOA")
        protected List<MOAMonetaryAmount> moa;
        @XmlElement(name = "SegGrp-3")
        protected List<DESTIM.SegGrp2 .SegGrp3> segGrp3;

        /**
         * Gets the value of the nad property.
         * 
         * @return
         *     possible object is
         *     {@link NADNameAndAddress }
         *     
         */
        public NADNameAndAddress getNAD() {
            return nad;
        }

        /**
         * Sets the value of the nad property.
         * 
         * @param value
         *     allowed object is
         *     {@link NADNameAndAddress }
         *     
         */
        public void setNAD(NADNameAndAddress value) {
            this.nad = value;
        }

        /**
         * Gets the value of the moa property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the moa property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMOA().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MOAMonetaryAmount }
         * 
         * 
         */
        public List<MOAMonetaryAmount> getMOA() {
            if (moa == null) {
                moa = new ArrayList<MOAMonetaryAmount>();
            }
            return this.moa;
        }

        /**
         * Gets the value of the segGrp3 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the segGrp3 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegGrp3().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DESTIM.SegGrp2 .SegGrp3 }
         * 
         * 
         */
        public List<DESTIM.SegGrp2 .SegGrp3> getSegGrp3() {
            if (segGrp3 == null) {
                segGrp3 = new ArrayList<DESTIM.SegGrp2 .SegGrp3>();
            }
            return this.segGrp3;
        }

        public DESTIM.SegGrp2 withNAD(NADNameAndAddress value) {
            setNAD(value);
            return this;
        }

        public DESTIM.SegGrp2 withMOA(MOAMonetaryAmount... values) {
            if (values!= null) {
                for (MOAMonetaryAmount value: values) {
                    getMOA().add(value);
                }
            }
            return this;
        }

        public DESTIM.SegGrp2 withMOA(Collection<MOAMonetaryAmount> values) {
            if (values!= null) {
                getMOA().addAll(values);
            }
            return this;
        }

        public DESTIM.SegGrp2 withSegGrp3(DESTIM.SegGrp2 .SegGrp3 ... values) {
            if (values!= null) {
                for (DESTIM.SegGrp2 .SegGrp3 value: values) {
                    getSegGrp3().add(value);
                }
            }
            return this;
        }

        public DESTIM.SegGrp2 withSegGrp3(Collection<DESTIM.SegGrp2 .SegGrp3> values) {
            if (values!= null) {
                getSegGrp3().addAll(values);
            }
            return this;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="CTA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}CTA-ContactInformation"/&gt;
         *           &lt;element name="COM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}COM-CommunicationContact" maxOccurs="9" minOccurs="0"/&gt;
         *         &lt;/sequence&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cta",
            "com"
        })
        public static class SegGrp3 {

            @XmlElement(name = "CTA", required = true)
            protected CTAContactInformation cta;
            @XmlElement(name = "COM")
            protected List<COMCommunicationContact> com;

            /**
             * Gets the value of the cta property.
             * 
             * @return
             *     possible object is
             *     {@link CTAContactInformation }
             *     
             */
            public CTAContactInformation getCTA() {
                return cta;
            }

            /**
             * Sets the value of the cta property.
             * 
             * @param value
             *     allowed object is
             *     {@link CTAContactInformation }
             *     
             */
            public void setCTA(CTAContactInformation value) {
                this.cta = value;
            }

            /**
             * Gets the value of the com property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the com property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCOM().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link COMCommunicationContact }
             * 
             * 
             */
            public List<COMCommunicationContact> getCOM() {
                if (com == null) {
                    com = new ArrayList<COMCommunicationContact>();
                }
                return this.com;
            }

            public DESTIM.SegGrp2 .SegGrp3 withCTA(CTAContactInformation value) {
                setCTA(value);
                return this;
            }

            public DESTIM.SegGrp2 .SegGrp3 withCOM(COMCommunicationContact... values) {
                if (values!= null) {
                    for (COMCommunicationContact value: values) {
                        getCOM().add(value);
                    }
                }
                return this;
            }

            public DESTIM.SegGrp2 .SegGrp3 withCOM(Collection<COMCommunicationContact> values) {
                if (values!= null) {
                    getCOM().addAll(values);
                }
                return this;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="TDT" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}TDT-TransportInformation"/&gt;
     *           &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="9" minOccurs="0"/&gt;
     *         &lt;/sequence&gt;
     *         &lt;element name="SegGrp-5" maxOccurs="9" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="LOC" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LOC-PlaceLocationIdentification"/&gt;
     *                     &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="9" minOccurs="0"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tdt",
        "dtm",
        "segGrp5"
    })
    public static class SegGrp4 {

        @XmlElement(name = "TDT", required = true)
        protected TDTTransportInformation tdt;
        @XmlElement(name = "DTM")
        protected List<DTMDateTimePeriod> dtm;
        @XmlElement(name = "SegGrp-5")
        protected List<DESTIM.SegGrp4 .SegGrp5> segGrp5;

        /**
         * Gets the value of the tdt property.
         * 
         * @return
         *     possible object is
         *     {@link TDTTransportInformation }
         *     
         */
        public TDTTransportInformation getTDT() {
            return tdt;
        }

        /**
         * Sets the value of the tdt property.
         * 
         * @param value
         *     allowed object is
         *     {@link TDTTransportInformation }
         *     
         */
        public void setTDT(TDTTransportInformation value) {
            this.tdt = value;
        }

        /**
         * Gets the value of the dtm property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the dtm property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDTM().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DTMDateTimePeriod }
         * 
         * 
         */
        public List<DTMDateTimePeriod> getDTM() {
            if (dtm == null) {
                dtm = new ArrayList<DTMDateTimePeriod>();
            }
            return this.dtm;
        }

        /**
         * Gets the value of the segGrp5 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the segGrp5 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegGrp5().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DESTIM.SegGrp4 .SegGrp5 }
         * 
         * 
         */
        public List<DESTIM.SegGrp4 .SegGrp5> getSegGrp5() {
            if (segGrp5 == null) {
                segGrp5 = new ArrayList<DESTIM.SegGrp4 .SegGrp5>();
            }
            return this.segGrp5;
        }

        public DESTIM.SegGrp4 withTDT(TDTTransportInformation value) {
            setTDT(value);
            return this;
        }

        public DESTIM.SegGrp4 withDTM(DTMDateTimePeriod... values) {
            if (values!= null) {
                for (DTMDateTimePeriod value: values) {
                    getDTM().add(value);
                }
            }
            return this;
        }

        public DESTIM.SegGrp4 withDTM(Collection<DTMDateTimePeriod> values) {
            if (values!= null) {
                getDTM().addAll(values);
            }
            return this;
        }

        public DESTIM.SegGrp4 withSegGrp5(DESTIM.SegGrp4 .SegGrp5 ... values) {
            if (values!= null) {
                for (DESTIM.SegGrp4 .SegGrp5 value: values) {
                    getSegGrp5().add(value);
                }
            }
            return this;
        }

        public DESTIM.SegGrp4 withSegGrp5(Collection<DESTIM.SegGrp4 .SegGrp5> values) {
            if (values!= null) {
                getSegGrp5().addAll(values);
            }
            return this;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="LOC" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LOC-PlaceLocationIdentification"/&gt;
         *           &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" maxOccurs="9" minOccurs="0"/&gt;
         *         &lt;/sequence&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "loc",
            "dtm"
        })
        public static class SegGrp5 {

            @XmlElement(name = "LOC", required = true)
            protected LOCPlaceLocationIdentification loc;
            @XmlElement(name = "DTM")
            protected List<DTMDateTimePeriod> dtm;

            /**
             * Gets the value of the loc property.
             * 
             * @return
             *     possible object is
             *     {@link LOCPlaceLocationIdentification }
             *     
             */
            public LOCPlaceLocationIdentification getLOC() {
                return loc;
            }

            /**
             * Sets the value of the loc property.
             * 
             * @param value
             *     allowed object is
             *     {@link LOCPlaceLocationIdentification }
             *     
             */
            public void setLOC(LOCPlaceLocationIdentification value) {
                this.loc = value;
            }

            /**
             * Gets the value of the dtm property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the dtm property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDTM().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DTMDateTimePeriod }
             * 
             * 
             */
            public List<DTMDateTimePeriod> getDTM() {
                if (dtm == null) {
                    dtm = new ArrayList<DTMDateTimePeriod>();
                }
                return this.dtm;
            }

            public DESTIM.SegGrp4 .SegGrp5 withLOC(LOCPlaceLocationIdentification value) {
                setLOC(value);
                return this;
            }

            public DESTIM.SegGrp4 .SegGrp5 withDTM(DTMDateTimePeriod... values) {
                if (values!= null) {
                    for (DTMDateTimePeriod value: values) {
                        getDTM().add(value);
                    }
                }
                return this;
            }

            public DESTIM.SegGrp4 .SegGrp5 withDTM(Collection<DTMDateTimePeriod> values) {
                if (values!= null) {
                    getDTM().addAll(values);
                }
                return this;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod"/&gt;
     *           &lt;element name="LOC" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LOC-PlaceLocationIdentification" minOccurs="0"/&gt;
     *           &lt;element name="NAD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}NAD-NameAndAddress" maxOccurs="9" minOccurs="0"/&gt;
     *         &lt;/sequence&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dtm",
        "loc",
        "nad"
    })
    public static class SegGrp6 {

        @XmlElement(name = "DTM", required = true)
        protected DTMDateTimePeriod dtm;
        @XmlElement(name = "LOC")
        protected LOCPlaceLocationIdentification loc;
        @XmlElement(name = "NAD")
        protected List<NADNameAndAddress> nad;

        /**
         * Gets the value of the dtm property.
         * 
         * @return
         *     possible object is
         *     {@link DTMDateTimePeriod }
         *     
         */
        public DTMDateTimePeriod getDTM() {
            return dtm;
        }

        /**
         * Sets the value of the dtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link DTMDateTimePeriod }
         *     
         */
        public void setDTM(DTMDateTimePeriod value) {
            this.dtm = value;
        }

        /**
         * Gets the value of the loc property.
         * 
         * @return
         *     possible object is
         *     {@link LOCPlaceLocationIdentification }
         *     
         */
        public LOCPlaceLocationIdentification getLOC() {
            return loc;
        }

        /**
         * Sets the value of the loc property.
         * 
         * @param value
         *     allowed object is
         *     {@link LOCPlaceLocationIdentification }
         *     
         */
        public void setLOC(LOCPlaceLocationIdentification value) {
            this.loc = value;
        }

        /**
         * Gets the value of the nad property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the nad property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNAD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NADNameAndAddress }
         * 
         * 
         */
        public List<NADNameAndAddress> getNAD() {
            if (nad == null) {
                nad = new ArrayList<NADNameAndAddress>();
            }
            return this.nad;
        }

        public DESTIM.SegGrp6 withDTM(DTMDateTimePeriod value) {
            setDTM(value);
            return this;
        }

        public DESTIM.SegGrp6 withLOC(LOCPlaceLocationIdentification value) {
            setLOC(value);
            return this;
        }

        public DESTIM.SegGrp6 withNAD(NADNameAndAddress... values) {
            if (values!= null) {
                for (NADNameAndAddress value: values) {
                    getNAD().add(value);
                }
            }
            return this;
        }

        public DESTIM.SegGrp6 withNAD(Collection<NADNameAndAddress> values) {
            if (values!= null) {
                getNAD().addAll(values);
            }
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="RFF" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RFF-Reference"/&gt;
     *           &lt;element name="DTM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DTM-DateTimePeriod" minOccurs="0"/&gt;
     *           &lt;element name="NAD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}NAD-NameAndAddress" maxOccurs="9" minOccurs="0"/&gt;
     *           &lt;element name="MOA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MOA-MonetaryAmount" minOccurs="0"/&gt;
     *         &lt;/sequence&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rff",
        "dtm",
        "nad",
        "moa"
    })
    public static class SegGrp7 {

        @XmlElement(name = "RFF", required = true)
        protected RFFReference rff;
        @XmlElement(name = "DTM")
        protected DTMDateTimePeriod dtm;
        @XmlElement(name = "NAD")
        protected List<NADNameAndAddress> nad;
        @XmlElement(name = "MOA")
        protected MOAMonetaryAmount moa;

        /**
         * Gets the value of the rff property.
         * 
         * @return
         *     possible object is
         *     {@link RFFReference }
         *     
         */
        public RFFReference getRFF() {
            return rff;
        }

        /**
         * Sets the value of the rff property.
         * 
         * @param value
         *     allowed object is
         *     {@link RFFReference }
         *     
         */
        public void setRFF(RFFReference value) {
            this.rff = value;
        }

        /**
         * Gets the value of the dtm property.
         * 
         * @return
         *     possible object is
         *     {@link DTMDateTimePeriod }
         *     
         */
        public DTMDateTimePeriod getDTM() {
            return dtm;
        }

        /**
         * Sets the value of the dtm property.
         * 
         * @param value
         *     allowed object is
         *     {@link DTMDateTimePeriod }
         *     
         */
        public void setDTM(DTMDateTimePeriod value) {
            this.dtm = value;
        }

        /**
         * Gets the value of the nad property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the nad property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getNAD().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NADNameAndAddress }
         * 
         * 
         */
        public List<NADNameAndAddress> getNAD() {
            if (nad == null) {
                nad = new ArrayList<NADNameAndAddress>();
            }
            return this.nad;
        }

        /**
         * Gets the value of the moa property.
         * 
         * @return
         *     possible object is
         *     {@link MOAMonetaryAmount }
         *     
         */
        public MOAMonetaryAmount getMOA() {
            return moa;
        }

        /**
         * Sets the value of the moa property.
         * 
         * @param value
         *     allowed object is
         *     {@link MOAMonetaryAmount }
         *     
         */
        public void setMOA(MOAMonetaryAmount value) {
            this.moa = value;
        }

        public DESTIM.SegGrp7 withRFF(RFFReference value) {
            setRFF(value);
            return this;
        }

        public DESTIM.SegGrp7 withDTM(DTMDateTimePeriod value) {
            setDTM(value);
            return this;
        }

        public DESTIM.SegGrp7 withNAD(NADNameAndAddress... values) {
            if (values!= null) {
                for (NADNameAndAddress value: values) {
                    getNAD().add(value);
                }
            }
            return this;
        }

        public DESTIM.SegGrp7 withNAD(Collection<NADNameAndAddress> values) {
            if (values!= null) {
                getNAD().addAll(values);
            }
            return this;
        }

        public DESTIM.SegGrp7 withMOA(MOAMonetaryAmount value) {
            setMOA(value);
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;sequence&gt;
     *           &lt;element name="LIN" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}LIN-LineItem"/&gt;
     *           &lt;element name="DIM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DIM-Dimensions" minOccurs="0"/&gt;
     *           &lt;element name="QTY" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}QTY-Quantity" minOccurs="0"/&gt;
     *           &lt;element name="FTX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}FTX-FreeText" maxOccurs="9" minOccurs="0"/&gt;
     *         &lt;/sequence&gt;
     *         &lt;element name="SegGrp-9" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="DAM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DAM-Damage"/&gt;
     *                     &lt;element name="COD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}COD-ComponentDetails" minOccurs="0"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="SegGrp-10" maxOccurs="9" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="RTE" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RTE-RateDetails"/&gt;
     *                     &lt;element name="QTY" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}QTY-Quantity"/&gt;
     *                   &lt;/sequence&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="SegGrp-11" maxOccurs="9" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;sequence&gt;
     *                     &lt;element name="NAD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}NAD-NameAndAddress"/&gt;
     *                   &lt;/sequence&gt;
     *                   &lt;element name="SegGrp-12" maxOccurs="9"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;sequence&gt;
     *                               &lt;element name="MOA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MOA-MonetaryAmount"/&gt;
     *                               &lt;element name="TAX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}TAX-DutyTaxFeeDetails" minOccurs="0"/&gt;
     *                               &lt;element name="MEA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MEA-Measurements" minOccurs="0"/&gt;
     *                             &lt;/sequence&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lin",
        "dim",
        "qty",
        "ftx",
        "segGrp9",
        "segGrp10",
        "segGrp11"
    })
    public static class SegGrp8 {

        @XmlElement(name = "LIN", required = true)
        protected LINLineItem lin;
        @XmlElement(name = "DIM")
        protected DIMDimensions dim;
        @XmlElement(name = "QTY")
        protected QTYQuantity qty;
        @XmlElement(name = "FTX")
        protected List<FTXFreeText> ftx;
        @XmlElement(name = "SegGrp-9")
        protected DESTIM.SegGrp8 .SegGrp9 segGrp9;
        @XmlElement(name = "SegGrp-10")
        protected List<DESTIM.SegGrp8 .SegGrp10> segGrp10;
        @XmlElement(name = "SegGrp-11")
        protected List<DESTIM.SegGrp8 .SegGrp11> segGrp11;

        /**
         * Gets the value of the lin property.
         * 
         * @return
         *     possible object is
         *     {@link LINLineItem }
         *     
         */
        public LINLineItem getLIN() {
            return lin;
        }

        /**
         * Sets the value of the lin property.
         * 
         * @param value
         *     allowed object is
         *     {@link LINLineItem }
         *     
         */
        public void setLIN(LINLineItem value) {
            this.lin = value;
        }

        /**
         * Gets the value of the dim property.
         * 
         * @return
         *     possible object is
         *     {@link DIMDimensions }
         *     
         */
        public DIMDimensions getDIM() {
            return dim;
        }

        /**
         * Sets the value of the dim property.
         * 
         * @param value
         *     allowed object is
         *     {@link DIMDimensions }
         *     
         */
        public void setDIM(DIMDimensions value) {
            this.dim = value;
        }

        /**
         * Gets the value of the qty property.
         * 
         * @return
         *     possible object is
         *     {@link QTYQuantity }
         *     
         */
        public QTYQuantity getQTY() {
            return qty;
        }

        /**
         * Sets the value of the qty property.
         * 
         * @param value
         *     allowed object is
         *     {@link QTYQuantity }
         *     
         */
        public void setQTY(QTYQuantity value) {
            this.qty = value;
        }

        /**
         * Gets the value of the ftx property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the ftx property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFTX().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FTXFreeText }
         * 
         * 
         */
        public List<FTXFreeText> getFTX() {
            if (ftx == null) {
                ftx = new ArrayList<FTXFreeText>();
            }
            return this.ftx;
        }

        /**
         * Gets the value of the segGrp9 property.
         * 
         * @return
         *     possible object is
         *     {@link DESTIM.SegGrp8 .SegGrp9 }
         *     
         */
        public DESTIM.SegGrp8 .SegGrp9 getSegGrp9() {
            return segGrp9;
        }

        /**
         * Sets the value of the segGrp9 property.
         * 
         * @param value
         *     allowed object is
         *     {@link DESTIM.SegGrp8 .SegGrp9 }
         *     
         */
        public void setSegGrp9(DESTIM.SegGrp8 .SegGrp9 value) {
            this.segGrp9 = value;
        }

        /**
         * Gets the value of the segGrp10 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the segGrp10 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegGrp10().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DESTIM.SegGrp8 .SegGrp10 }
         * 
         * 
         */
        public List<DESTIM.SegGrp8 .SegGrp10> getSegGrp10() {
            if (segGrp10 == null) {
                segGrp10 = new ArrayList<DESTIM.SegGrp8 .SegGrp10>();
            }
            return this.segGrp10;
        }

        /**
         * Gets the value of the segGrp11 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the segGrp11 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegGrp11().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DESTIM.SegGrp8 .SegGrp11 }
         * 
         * 
         */
        public List<DESTIM.SegGrp8 .SegGrp11> getSegGrp11() {
            if (segGrp11 == null) {
                segGrp11 = new ArrayList<DESTIM.SegGrp8 .SegGrp11>();
            }
            return this.segGrp11;
        }

        public DESTIM.SegGrp8 withLIN(LINLineItem value) {
            setLIN(value);
            return this;
        }

        public DESTIM.SegGrp8 withDIM(DIMDimensions value) {
            setDIM(value);
            return this;
        }

        public DESTIM.SegGrp8 withQTY(QTYQuantity value) {
            setQTY(value);
            return this;
        }

        public DESTIM.SegGrp8 withFTX(FTXFreeText... values) {
            if (values!= null) {
                for (FTXFreeText value: values) {
                    getFTX().add(value);
                }
            }
            return this;
        }

        public DESTIM.SegGrp8 withFTX(Collection<FTXFreeText> values) {
            if (values!= null) {
                getFTX().addAll(values);
            }
            return this;
        }

        public DESTIM.SegGrp8 withSegGrp9(DESTIM.SegGrp8 .SegGrp9 value) {
            setSegGrp9(value);
            return this;
        }

        public DESTIM.SegGrp8 withSegGrp10(DESTIM.SegGrp8 .SegGrp10 ... values) {
            if (values!= null) {
                for (DESTIM.SegGrp8 .SegGrp10 value: values) {
                    getSegGrp10().add(value);
                }
            }
            return this;
        }

        public DESTIM.SegGrp8 withSegGrp10(Collection<DESTIM.SegGrp8 .SegGrp10> values) {
            if (values!= null) {
                getSegGrp10().addAll(values);
            }
            return this;
        }

        public DESTIM.SegGrp8 withSegGrp11(DESTIM.SegGrp8 .SegGrp11 ... values) {
            if (values!= null) {
                for (DESTIM.SegGrp8 .SegGrp11 value: values) {
                    getSegGrp11().add(value);
                }
            }
            return this;
        }

        public DESTIM.SegGrp8 withSegGrp11(Collection<DESTIM.SegGrp8 .SegGrp11> values) {
            if (values!= null) {
                getSegGrp11().addAll(values);
            }
            return this;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="RTE" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}RTE-RateDetails"/&gt;
         *           &lt;element name="QTY" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}QTY-Quantity"/&gt;
         *         &lt;/sequence&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rte",
            "qty"
        })
        public static class SegGrp10 {

            @XmlElement(name = "RTE", required = true)
            protected RTERateDetails rte;
            @XmlElement(name = "QTY", required = true)
            protected QTYQuantity qty;

            /**
             * Gets the value of the rte property.
             * 
             * @return
             *     possible object is
             *     {@link RTERateDetails }
             *     
             */
            public RTERateDetails getRTE() {
                return rte;
            }

            /**
             * Sets the value of the rte property.
             * 
             * @param value
             *     allowed object is
             *     {@link RTERateDetails }
             *     
             */
            public void setRTE(RTERateDetails value) {
                this.rte = value;
            }

            /**
             * Gets the value of the qty property.
             * 
             * @return
             *     possible object is
             *     {@link QTYQuantity }
             *     
             */
            public QTYQuantity getQTY() {
                return qty;
            }

            /**
             * Sets the value of the qty property.
             * 
             * @param value
             *     allowed object is
             *     {@link QTYQuantity }
             *     
             */
            public void setQTY(QTYQuantity value) {
                this.qty = value;
            }

            public DESTIM.SegGrp8 .SegGrp10 withRTE(RTERateDetails value) {
                setRTE(value);
                return this;
            }

            public DESTIM.SegGrp8 .SegGrp10 withQTY(QTYQuantity value) {
                setQTY(value);
                return this;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="NAD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}NAD-NameAndAddress"/&gt;
         *         &lt;/sequence&gt;
         *         &lt;element name="SegGrp-12" maxOccurs="9"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;sequence&gt;
         *                     &lt;element name="MOA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MOA-MonetaryAmount"/&gt;
         *                     &lt;element name="TAX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}TAX-DutyTaxFeeDetails" minOccurs="0"/&gt;
         *                     &lt;element name="MEA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MEA-Measurements" minOccurs="0"/&gt;
         *                   &lt;/sequence&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nad",
            "segGrp12"
        })
        public static class SegGrp11 {

            @XmlElement(name = "NAD", required = true)
            protected NADNameAndAddress nad;
            @XmlElement(name = "SegGrp-12", required = true)
            protected List<DESTIM.SegGrp8 .SegGrp11 .SegGrp12> segGrp12;

            /**
             * Gets the value of the nad property.
             * 
             * @return
             *     possible object is
             *     {@link NADNameAndAddress }
             *     
             */
            public NADNameAndAddress getNAD() {
                return nad;
            }

            /**
             * Sets the value of the nad property.
             * 
             * @param value
             *     allowed object is
             *     {@link NADNameAndAddress }
             *     
             */
            public void setNAD(NADNameAndAddress value) {
                this.nad = value;
            }

            /**
             * Gets the value of the segGrp12 property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the segGrp12 property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSegGrp12().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DESTIM.SegGrp8 .SegGrp11 .SegGrp12 }
             * 
             * 
             */
            public List<DESTIM.SegGrp8 .SegGrp11 .SegGrp12> getSegGrp12() {
                if (segGrp12 == null) {
                    segGrp12 = new ArrayList<DESTIM.SegGrp8 .SegGrp11 .SegGrp12>();
                }
                return this.segGrp12;
            }

            public DESTIM.SegGrp8 .SegGrp11 withNAD(NADNameAndAddress value) {
                setNAD(value);
                return this;
            }

            public DESTIM.SegGrp8 .SegGrp11 withSegGrp12(DESTIM.SegGrp8 .SegGrp11 .SegGrp12 ... values) {
                if (values!= null) {
                    for (DESTIM.SegGrp8 .SegGrp11 .SegGrp12 value: values) {
                        getSegGrp12().add(value);
                    }
                }
                return this;
            }

            public DESTIM.SegGrp8 .SegGrp11 withSegGrp12(Collection<DESTIM.SegGrp8 .SegGrp11 .SegGrp12> values) {
                if (values!= null) {
                    getSegGrp12().addAll(values);
                }
                return this;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;sequence&gt;
             *           &lt;element name="MOA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MOA-MonetaryAmount"/&gt;
             *           &lt;element name="TAX" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}TAX-DutyTaxFeeDetails" minOccurs="0"/&gt;
             *           &lt;element name="MEA" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}MEA-Measurements" minOccurs="0"/&gt;
             *         &lt;/sequence&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "moa",
                "tax",
                "mea"
            })
            public static class SegGrp12 {

                @XmlElement(name = "MOA", required = true)
                protected MOAMonetaryAmount moa;
                @XmlElement(name = "TAX")
                protected TAXDutyTaxFeeDetails tax;
                @XmlElement(name = "MEA")
                protected MEAMeasurements mea;

                /**
                 * Gets the value of the moa property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MOAMonetaryAmount }
                 *     
                 */
                public MOAMonetaryAmount getMOA() {
                    return moa;
                }

                /**
                 * Sets the value of the moa property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MOAMonetaryAmount }
                 *     
                 */
                public void setMOA(MOAMonetaryAmount value) {
                    this.moa = value;
                }

                /**
                 * Gets the value of the tax property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TAXDutyTaxFeeDetails }
                 *     
                 */
                public TAXDutyTaxFeeDetails getTAX() {
                    return tax;
                }

                /**
                 * Sets the value of the tax property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TAXDutyTaxFeeDetails }
                 *     
                 */
                public void setTAX(TAXDutyTaxFeeDetails value) {
                    this.tax = value;
                }

                /**
                 * Gets the value of the mea property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MEAMeasurements }
                 *     
                 */
                public MEAMeasurements getMEA() {
                    return mea;
                }

                /**
                 * Sets the value of the mea property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MEAMeasurements }
                 *     
                 */
                public void setMEA(MEAMeasurements value) {
                    this.mea = value;
                }

                public DESTIM.SegGrp8 .SegGrp11 .SegGrp12 withMOA(MOAMonetaryAmount value) {
                    setMOA(value);
                    return this;
                }

                public DESTIM.SegGrp8 .SegGrp11 .SegGrp12 withTAX(TAXDutyTaxFeeDetails value) {
                    setTAX(value);
                    return this;
                }

                public DESTIM.SegGrp8 .SegGrp11 .SegGrp12 withMEA(MEAMeasurements value) {
                    setMEA(value);
                    return this;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;sequence&gt;
         *           &lt;element name="DAM" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}DAM-Damage"/&gt;
         *           &lt;element name="COD" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}COD-ComponentDetails" minOccurs="0"/&gt;
         *         &lt;/sequence&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dam",
            "cod"
        })
        public static class SegGrp9 {

            @XmlElement(name = "DAM", required = true)
            protected DAMDamage dam;
            @XmlElement(name = "COD")
            protected CODComponentDetails cod;

            /**
             * Gets the value of the dam property.
             * 
             * @return
             *     possible object is
             *     {@link DAMDamage }
             *     
             */
            public DAMDamage getDAM() {
                return dam;
            }

            /**
             * Sets the value of the dam property.
             * 
             * @param value
             *     allowed object is
             *     {@link DAMDamage }
             *     
             */
            public void setDAM(DAMDamage value) {
                this.dam = value;
            }

            /**
             * Gets the value of the cod property.
             * 
             * @return
             *     possible object is
             *     {@link CODComponentDetails }
             *     
             */
            public CODComponentDetails getCOD() {
                return cod;
            }

            /**
             * Sets the value of the cod property.
             * 
             * @param value
             *     allowed object is
             *     {@link CODComponentDetails }
             *     
             */
            public void setCOD(CODComponentDetails value) {
                this.cod = value;
            }

            public DESTIM.SegGrp8 .SegGrp9 withDAM(DAMDamage value) {
                setDAM(value);
                return this;
            }

            public DESTIM.SegGrp8 .SegGrp9 withCOD(CODComponentDetails value) {
                setCOD(value);
                return this;
            }

        }

    }

}
