/*-
 * ========================LICENSE_START=================================
 * d16b-edifact-binding
 * %%
 * Copyright (C) 2020 - 2024 Smooks
 * %%
 * Licensed under the terms of the Apache License Version 2.0, or
 * the GNU Lesser General Public License version 3.0 or later.
 * 
 * SPDX-License-Identifier: Apache-2.0 OR LGPL-3.0-or-later
 * 
 * ======================================================================
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * ======================================================================
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * =========================LICENSE_END==================================
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.17 at 06:20:44 PM UTC 
//


package org.smooks.edifact.binding.d16b;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for C402-PackageTypeIdentification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="C402-PackageTypeIdentification"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="E7077" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E7077-DescriptionFormatCode"/&gt;
 *         &lt;element name="E7064a" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E7064-TypeOfPackages"/&gt;
 *         &lt;element name="E7143a" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E7143-ItemTypeIdentificationCode" minOccurs="0"/&gt;
 *         &lt;element name="E7064b" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E7064-TypeOfPackages" minOccurs="0"/&gt;
 *         &lt;element name="E7143b" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E7143-ItemTypeIdentificationCode" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "C402-PackageTypeIdentification", propOrder = {
    "e7077",
    "e7064A",
    "e7143A",
    "e7064B",
    "e7143B"
})
public class C402PackageTypeIdentification {

    @XmlElement(name = "E7077", required = true)
    @XmlSchemaType(name = "string")
    protected E7077DescriptionFormatCode e7077;
    @XmlElement(name = "E7064a", required = true)
    protected String e7064A;
    @XmlElement(name = "E7143a")
    @XmlSchemaType(name = "string")
    protected E7143ItemTypeIdentificationCode e7143A;
    @XmlElement(name = "E7064b")
    protected String e7064B;
    @XmlElement(name = "E7143b")
    @XmlSchemaType(name = "string")
    protected E7143ItemTypeIdentificationCode e7143B;

    /**
     * Gets the value of the e7077 property.
     * 
     * @return
     *     possible object is
     *     {@link E7077DescriptionFormatCode }
     *     
     */
    public E7077DescriptionFormatCode getE7077() {
        return e7077;
    }

    /**
     * Sets the value of the e7077 property.
     * 
     * @param value
     *     allowed object is
     *     {@link E7077DescriptionFormatCode }
     *     
     */
    public void setE7077(E7077DescriptionFormatCode value) {
        this.e7077 = value;
    }

    /**
     * Gets the value of the e7064A property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE7064A() {
        return e7064A;
    }

    /**
     * Sets the value of the e7064A property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE7064A(String value) {
        this.e7064A = value;
    }

    /**
     * Gets the value of the e7143A property.
     * 
     * @return
     *     possible object is
     *     {@link E7143ItemTypeIdentificationCode }
     *     
     */
    public E7143ItemTypeIdentificationCode getE7143A() {
        return e7143A;
    }

    /**
     * Sets the value of the e7143A property.
     * 
     * @param value
     *     allowed object is
     *     {@link E7143ItemTypeIdentificationCode }
     *     
     */
    public void setE7143A(E7143ItemTypeIdentificationCode value) {
        this.e7143A = value;
    }

    /**
     * Gets the value of the e7064B property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE7064B() {
        return e7064B;
    }

    /**
     * Sets the value of the e7064B property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE7064B(String value) {
        this.e7064B = value;
    }

    /**
     * Gets the value of the e7143B property.
     * 
     * @return
     *     possible object is
     *     {@link E7143ItemTypeIdentificationCode }
     *     
     */
    public E7143ItemTypeIdentificationCode getE7143B() {
        return e7143B;
    }

    /**
     * Sets the value of the e7143B property.
     * 
     * @param value
     *     allowed object is
     *     {@link E7143ItemTypeIdentificationCode }
     *     
     */
    public void setE7143B(E7143ItemTypeIdentificationCode value) {
        this.e7143B = value;
    }

    public C402PackageTypeIdentification withE7077(E7077DescriptionFormatCode value) {
        setE7077(value);
        return this;
    }

    public C402PackageTypeIdentification withE7064A(String value) {
        setE7064A(value);
        return this;
    }

    public C402PackageTypeIdentification withE7143A(E7143ItemTypeIdentificationCode value) {
        setE7143A(value);
        return this;
    }

    public C402PackageTypeIdentification withE7064B(String value) {
        setE7064B(value);
        return this;
    }

    public C402PackageTypeIdentification withE7143B(E7143ItemTypeIdentificationCode value) {
        setE7143B(value);
        return this;
    }

}
