/*-
 * ========================LICENSE_START=================================
 * d16b-edifact-binding
 * %%
 * Copyright (C) 2020 - 2024 Smooks
 * %%
 * Licensed under the terms of the Apache License Version 2.0, or
 * the GNU Lesser General Public License version 3.0 or later.
 * 
 * SPDX-License-Identifier: Apache-2.0 OR LGPL-3.0-or-later
 * 
 * ======================================================================
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * ======================================================================
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 * =========================LICENSE_END==================================
 */
//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.17 at 06:20:44 PM UTC 
//


package org.smooks.edifact.binding.d16b;

import java.math.BigDecimal;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for C174-ValueRange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="C174-ValueRange"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="E6411" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E6411-MeasurementUnitCode" minOccurs="0"/&gt;
 *         &lt;element name="E6314" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E6314-Measure" minOccurs="0"/&gt;
 *         &lt;element name="E6162" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E6162-RangeMinimumQuantity" minOccurs="0"/&gt;
 *         &lt;element name="E6152" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E6152-RangeMaximumQuantity" minOccurs="0"/&gt;
 *         &lt;element name="E6432" type="{http://www.ibm.com/dfdl/edi/un/edifact/D16B}E6432-SignificantDigitsQuantity" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "C174-ValueRange", propOrder = {
    "e6411",
    "e6314",
    "e6162",
    "e6152",
    "e6432"
})
public class C174ValueRange {

    @XmlElement(name = "E6411")
    protected String e6411;
    @XmlElement(name = "E6314")
    protected String e6314;
    @XmlElement(name = "E6162")
    protected BigDecimal e6162;
    @XmlElement(name = "E6152")
    protected BigDecimal e6152;
    @XmlElement(name = "E6432")
    protected BigDecimal e6432;

    /**
     * Gets the value of the e6411 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE6411() {
        return e6411;
    }

    /**
     * Sets the value of the e6411 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE6411(String value) {
        this.e6411 = value;
    }

    /**
     * Gets the value of the e6314 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getE6314() {
        return e6314;
    }

    /**
     * Sets the value of the e6314 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setE6314(String value) {
        this.e6314 = value;
    }

    /**
     * Gets the value of the e6162 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getE6162() {
        return e6162;
    }

    /**
     * Sets the value of the e6162 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setE6162(BigDecimal value) {
        this.e6162 = value;
    }

    /**
     * Gets the value of the e6152 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getE6152() {
        return e6152;
    }

    /**
     * Sets the value of the e6152 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setE6152(BigDecimal value) {
        this.e6152 = value;
    }

    /**
     * Gets the value of the e6432 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getE6432() {
        return e6432;
    }

    /**
     * Sets the value of the e6432 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setE6432(BigDecimal value) {
        this.e6432 = value;
    }

    public C174ValueRange withE6411(String value) {
        setE6411(value);
        return this;
    }

    public C174ValueRange withE6314(String value) {
        setE6314(value);
        return this;
    }

    public C174ValueRange withE6162(BigDecimal value) {
        setE6162(value);
        return this;
    }

    public C174ValueRange withE6152(BigDecimal value) {
        setE6152(value);
        return this;
    }

    public C174ValueRange withE6432(BigDecimal value) {
        setE6432(value);
        return this;
    }

}
