/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.DAPLOS;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.CCICharacteristicClassId;    
import org.milyn.edi.unedifact.d17a.common.CAVCharacteristicValue;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup17 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private CCICharacteristicClassId cCICharacteristicClassId;
    private CAVCharacteristicValue cAVCharacteristicValue;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(cCICharacteristicClassId != null) {
            nodeWriter.write("CCI");
            nodeWriter.write(delimiters.getField());
            cCICharacteristicClassId.write(nodeWriter, delimiters);
        }
        if(cAVCharacteristicValue != null) {
            nodeWriter.write("CAV");
            nodeWriter.write(delimiters.getField());
            cAVCharacteristicValue.write(nodeWriter, delimiters);
        }
    }

    public CCICharacteristicClassId getCCICharacteristicClassId() {
        return cCICharacteristicClassId;
    }

    public SegmentGroup17 setCCICharacteristicClassId(CCICharacteristicClassId cCICharacteristicClassId) {
        this.cCICharacteristicClassId = cCICharacteristicClassId;  return this;
    }

    public CAVCharacteristicValue getCAVCharacteristicValue() {
        return cAVCharacteristicValue;
    }

    public SegmentGroup17 setCAVCharacteristicValue(CAVCharacteristicValue cAVCharacteristicValue) {
        this.cAVCharacteristicValue = cAVCharacteristicValue;  return this;
    }
}