/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.DAPLOS;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.HYNHierarchyInformation;    
import java.util.List;    
import org.milyn.edi.unedifact.d17a.common.PIAAdditionalProductId;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup8 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private HYNHierarchyInformation hYNHierarchyInformation;
    private List<PIAAdditionalProductId> pIAAdditionalProductId;
    private List<SegmentGroup9> segmentGroup9;
    private List<SegmentGroup10> segmentGroup10;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(hYNHierarchyInformation != null) {
            nodeWriter.write("HYN");
            nodeWriter.write(delimiters.getField());
            hYNHierarchyInformation.write(nodeWriter, delimiters);
        }
        if(pIAAdditionalProductId != null && !pIAAdditionalProductId.isEmpty()) {
            for(PIAAdditionalProductId pIAAdditionalProductIdInst : pIAAdditionalProductId) {
                nodeWriter.write("PIA");
                nodeWriter.write(delimiters.getField());
                pIAAdditionalProductIdInst.write(nodeWriter, delimiters);
            }
        }
        if(segmentGroup9 != null && !segmentGroup9.isEmpty()) {
            for(SegmentGroup9 segmentGroup9Inst : segmentGroup9) {
                segmentGroup9Inst.write(nodeWriter, delimiters);
            }
        }
        if(segmentGroup10 != null && !segmentGroup10.isEmpty()) {
            for(SegmentGroup10 segmentGroup10Inst : segmentGroup10) {
                segmentGroup10Inst.write(nodeWriter, delimiters);
            }
        }
    }

    public HYNHierarchyInformation getHYNHierarchyInformation() {
        return hYNHierarchyInformation;
    }

    public SegmentGroup8 setHYNHierarchyInformation(HYNHierarchyInformation hYNHierarchyInformation) {
        this.hYNHierarchyInformation = hYNHierarchyInformation;  return this;
    }

    public List<PIAAdditionalProductId> getPIAAdditionalProductId() {
        return pIAAdditionalProductId;
    }

    public SegmentGroup8 setPIAAdditionalProductId(List<PIAAdditionalProductId> pIAAdditionalProductId) {
        this.pIAAdditionalProductId = pIAAdditionalProductId;  return this;
    }

    public List<SegmentGroup9> getSegmentGroup9() {
        return segmentGroup9;
    }

    public SegmentGroup8 setSegmentGroup9(List<SegmentGroup9> segmentGroup9) {
        this.segmentGroup9 = segmentGroup9;  return this;
    }

    public List<SegmentGroup10> getSegmentGroup10() {
        return segmentGroup10;
    }

    public SegmentGroup8 setSegmentGroup10(List<SegmentGroup10> segmentGroup10) {
        this.segmentGroup10 = segmentGroup10;  return this;
    }
}