/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.RECADV;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.DOCDocumentMessageDetails;    
import java.util.List;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup29 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private DOCDocumentMessageDetails dOCDocumentMessageDetails;
    private List<SegmentGroup30> segmentGroup30;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(dOCDocumentMessageDetails != null) {
            nodeWriter.write("DOC");
            nodeWriter.write(delimiters.getField());
            dOCDocumentMessageDetails.write(nodeWriter, delimiters);
        }
        if(segmentGroup30 != null && !segmentGroup30.isEmpty()) {
            for(SegmentGroup30 segmentGroup30Inst : segmentGroup30) {
                segmentGroup30Inst.write(nodeWriter, delimiters);
            }
        }
    }

    public DOCDocumentMessageDetails getDOCDocumentMessageDetails() {
        return dOCDocumentMessageDetails;
    }

    public SegmentGroup29 setDOCDocumentMessageDetails(DOCDocumentMessageDetails dOCDocumentMessageDetails) {
        this.dOCDocumentMessageDetails = dOCDocumentMessageDetails;  return this;
    }

    public List<SegmentGroup30> getSegmentGroup30() {
        return segmentGroup30;
    }

    public SegmentGroup29 setSegmentGroup30(List<SegmentGroup30> segmentGroup30) {
        this.segmentGroup30 = segmentGroup30;  return this;
    }
}