/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.RECORD;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.LOCPlaceLocationIdentification;    
import java.util.List;    
import org.milyn.edi.unedifact.d17a.common.MEAMeasurements;    
import org.milyn.edi.unedifact.d17a.common.ADRAddress;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup6 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private LOCPlaceLocationIdentification lOCPlaceLocationIdentification;
    private List<MEAMeasurements> mEAMeasurements;
    private ADRAddress aDRAddress;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(lOCPlaceLocationIdentification != null) {
            nodeWriter.write("LOC");
            nodeWriter.write(delimiters.getField());
            lOCPlaceLocationIdentification.write(nodeWriter, delimiters);
        }
        if(mEAMeasurements != null && !mEAMeasurements.isEmpty()) {
            for(MEAMeasurements mEAMeasurementsInst : mEAMeasurements) {
                nodeWriter.write("MEA");
                nodeWriter.write(delimiters.getField());
                mEAMeasurementsInst.write(nodeWriter, delimiters);
            }
        }
        if(aDRAddress != null) {
            nodeWriter.write("ADR");
            nodeWriter.write(delimiters.getField());
            aDRAddress.write(nodeWriter, delimiters);
        }
    }

    public LOCPlaceLocationIdentification getLOCPlaceLocationIdentification() {
        return lOCPlaceLocationIdentification;
    }

    public SegmentGroup6 setLOCPlaceLocationIdentification(LOCPlaceLocationIdentification lOCPlaceLocationIdentification) {
        this.lOCPlaceLocationIdentification = lOCPlaceLocationIdentification;  return this;
    }

    public List<MEAMeasurements> getMEAMeasurements() {
        return mEAMeasurements;
    }

    public SegmentGroup6 setMEAMeasurements(List<MEAMeasurements> mEAMeasurements) {
        this.mEAMeasurements = mEAMeasurements;  return this;
    }

    public ADRAddress getADRAddress() {
        return aDRAddress;
    }

    public SegmentGroup6 setADRAddress(ADRAddress aDRAddress) {
        this.aDRAddress = aDRAddress;  return this;
    }
}