/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.INSRPT;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.GINGoodsIdentityNumber;    
import java.util.List;    
import org.milyn.edi.unedifact.d17a.common.RFFReference;    
import org.milyn.edi.unedifact.d17a.common.STSStatus;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup9 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private GINGoodsIdentityNumber gINGoodsIdentityNumber;
    private List<RFFReference> rFFReference;
    private List<STSStatus> sTSStatus;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(gINGoodsIdentityNumber != null) {
            nodeWriter.write("GIN");
            nodeWriter.write(delimiters.getField());
            gINGoodsIdentityNumber.write(nodeWriter, delimiters);
        }
        if(rFFReference != null && !rFFReference.isEmpty()) {
            for(RFFReference rFFReferenceInst : rFFReference) {
                nodeWriter.write("RFF");
                nodeWriter.write(delimiters.getField());
                rFFReferenceInst.write(nodeWriter, delimiters);
            }
        }
        if(sTSStatus != null && !sTSStatus.isEmpty()) {
            for(STSStatus sTSStatusInst : sTSStatus) {
                nodeWriter.write("STS");
                nodeWriter.write(delimiters.getField());
                sTSStatusInst.write(nodeWriter, delimiters);
            }
        }
    }

    public GINGoodsIdentityNumber getGINGoodsIdentityNumber() {
        return gINGoodsIdentityNumber;
    }

    public SegmentGroup9 setGINGoodsIdentityNumber(GINGoodsIdentityNumber gINGoodsIdentityNumber) {
        this.gINGoodsIdentityNumber = gINGoodsIdentityNumber;  return this;
    }

    public List<RFFReference> getRFFReference() {
        return rFFReference;
    }

    public SegmentGroup9 setRFFReference(List<RFFReference> rFFReference) {
        this.rFFReference = rFFReference;  return this;
    }

    public List<STSStatus> getSTSStatus() {
        return sTSStatus;
    }

    public SegmentGroup9 setSTSStatus(List<STSStatus> sTSStatus) {
        this.sTSStatus = sTSStatus;  return this;
    }
}