/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.STLRPT;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.CUXCurrencies;    
import org.milyn.edi.unedifact.d17a.common.EQNNumberOfUnits;    
import java.util.List;    
import org.milyn.edi.unedifact.d17a.common.MOAMonetaryAmount;    
import org.milyn.edi.unedifact.d17a.common.QVRQuantityVariances;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup3 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private CUXCurrencies cUXCurrencies;
    private EQNNumberOfUnits eQNNumberOfUnits;
    private List<MOAMonetaryAmount> mOAMonetaryAmount;
    private QVRQuantityVariances qVRQuantityVariances;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(cUXCurrencies != null) {
            nodeWriter.write("CUX");
            nodeWriter.write(delimiters.getField());
            cUXCurrencies.write(nodeWriter, delimiters);
        }
        if(eQNNumberOfUnits != null) {
            nodeWriter.write("EQN");
            nodeWriter.write(delimiters.getField());
            eQNNumberOfUnits.write(nodeWriter, delimiters);
        }
        if(mOAMonetaryAmount != null && !mOAMonetaryAmount.isEmpty()) {
            for(MOAMonetaryAmount mOAMonetaryAmountInst : mOAMonetaryAmount) {
                nodeWriter.write("MOA");
                nodeWriter.write(delimiters.getField());
                mOAMonetaryAmountInst.write(nodeWriter, delimiters);
            }
        }
        if(qVRQuantityVariances != null) {
            nodeWriter.write("QVR");
            nodeWriter.write(delimiters.getField());
            qVRQuantityVariances.write(nodeWriter, delimiters);
        }
    }

    public CUXCurrencies getCUXCurrencies() {
        return cUXCurrencies;
    }

    public SegmentGroup3 setCUXCurrencies(CUXCurrencies cUXCurrencies) {
        this.cUXCurrencies = cUXCurrencies;  return this;
    }

    public EQNNumberOfUnits getEQNNumberOfUnits() {
        return eQNNumberOfUnits;
    }

    public SegmentGroup3 setEQNNumberOfUnits(EQNNumberOfUnits eQNNumberOfUnits) {
        this.eQNNumberOfUnits = eQNNumberOfUnits;  return this;
    }

    public List<MOAMonetaryAmount> getMOAMonetaryAmount() {
        return mOAMonetaryAmount;
    }

    public SegmentGroup3 setMOAMonetaryAmount(List<MOAMonetaryAmount> mOAMonetaryAmount) {
        this.mOAMonetaryAmount = mOAMonetaryAmount;  return this;
    }

    public QVRQuantityVariances getQVRQuantityVariances() {
        return qVRQuantityVariances;
    }

    public SegmentGroup3 setQVRQuantityVariances(QVRQuantityVariances qVRQuantityVariances) {
        this.qVRQuantityVariances = qVRQuantityVariances;  return this;
    }
}