/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.RETINS;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.DGSDangerousGoods;    
import java.util.List;    
import org.milyn.edi.unedifact.d17a.common.QTYQuantity;    
import org.milyn.edi.unedifact.d17a.common.FTXFreeText;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup14 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private DGSDangerousGoods dGSDangerousGoods;
    private List<QTYQuantity> qTYQuantity;
    private List<FTXFreeText> fTXFreeText;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(dGSDangerousGoods != null) {
            nodeWriter.write("DGS");
            nodeWriter.write(delimiters.getField());
            dGSDangerousGoods.write(nodeWriter, delimiters);
        }
        if(qTYQuantity != null && !qTYQuantity.isEmpty()) {
            for(QTYQuantity qTYQuantityInst : qTYQuantity) {
                nodeWriter.write("QTY");
                nodeWriter.write(delimiters.getField());
                qTYQuantityInst.write(nodeWriter, delimiters);
            }
        }
        if(fTXFreeText != null && !fTXFreeText.isEmpty()) {
            for(FTXFreeText fTXFreeTextInst : fTXFreeText) {
                nodeWriter.write("FTX");
                nodeWriter.write(delimiters.getField());
                fTXFreeTextInst.write(nodeWriter, delimiters);
            }
        }
    }

    public DGSDangerousGoods getDGSDangerousGoods() {
        return dGSDangerousGoods;
    }

    public SegmentGroup14 setDGSDangerousGoods(DGSDangerousGoods dGSDangerousGoods) {
        this.dGSDangerousGoods = dGSDangerousGoods;  return this;
    }

    public List<QTYQuantity> getQTYQuantity() {
        return qTYQuantity;
    }

    public SegmentGroup14 setQTYQuantity(List<QTYQuantity> qTYQuantity) {
        this.qTYQuantity = qTYQuantity;  return this;
    }

    public List<FTXFreeText> getFTXFreeText() {
        return fTXFreeText;
    }

    public SegmentGroup14 setFTXFreeText(List<FTXFreeText> fTXFreeText) {
        this.fTXFreeText = fTXFreeText;  return this;
    }
}