/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.QALITY;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.STAStatistics;    
import java.util.List;    
import org.milyn.edi.unedifact.d17a.common.DTMDateTimePeriod;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup26 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private STAStatistics sTAStatistics;
    private List<DTMDateTimePeriod> dTMDateTimePeriod;
    private List<SegmentGroup27> segmentGroup27;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(sTAStatistics != null) {
            nodeWriter.write("STA");
            nodeWriter.write(delimiters.getField());
            sTAStatistics.write(nodeWriter, delimiters);
        }
        if(dTMDateTimePeriod != null && !dTMDateTimePeriod.isEmpty()) {
            for(DTMDateTimePeriod dTMDateTimePeriodInst : dTMDateTimePeriod) {
                nodeWriter.write("DTM");
                nodeWriter.write(delimiters.getField());
                dTMDateTimePeriodInst.write(nodeWriter, delimiters);
            }
        }
        if(segmentGroup27 != null && !segmentGroup27.isEmpty()) {
            for(SegmentGroup27 segmentGroup27Inst : segmentGroup27) {
                segmentGroup27Inst.write(nodeWriter, delimiters);
            }
        }
    }

    public STAStatistics getSTAStatistics() {
        return sTAStatistics;
    }

    public SegmentGroup26 setSTAStatistics(STAStatistics sTAStatistics) {
        this.sTAStatistics = sTAStatistics;  return this;
    }

    public List<DTMDateTimePeriod> getDTMDateTimePeriod() {
        return dTMDateTimePeriod;
    }

    public SegmentGroup26 setDTMDateTimePeriod(List<DTMDateTimePeriod> dTMDateTimePeriod) {
        this.dTMDateTimePeriod = dTMDateTimePeriod;  return this;
    }

    public List<SegmentGroup27> getSegmentGroup27() {
        return segmentGroup27;
    }

    public SegmentGroup26 setSegmentGroup27(List<SegmentGroup27> segmentGroup27) {
        this.segmentGroup27 = segmentGroup27;  return this;
    }
}