/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.ORDCHG;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.CTAContactInformation;    
import java.util.List;    
import org.milyn.edi.unedifact.d17a.common.COMCommunicationContact;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup43 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private CTAContactInformation cTAContactInformation;
    private List<COMCommunicationContact> cOMCommunicationContact;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(cTAContactInformation != null) {
            nodeWriter.write("CTA");
            nodeWriter.write(delimiters.getField());
            cTAContactInformation.write(nodeWriter, delimiters);
        }
        if(cOMCommunicationContact != null && !cOMCommunicationContact.isEmpty()) {
            for(COMCommunicationContact cOMCommunicationContactInst : cOMCommunicationContact) {
                nodeWriter.write("COM");
                nodeWriter.write(delimiters.getField());
                cOMCommunicationContactInst.write(nodeWriter, delimiters);
            }
        }
    }

    public CTAContactInformation getCTAContactInformation() {
        return cTAContactInformation;
    }

    public SegmentGroup43 setCTAContactInformation(CTAContactInformation cTAContactInformation) {
        this.cTAContactInformation = cTAContactInformation;  return this;
    }

    public List<COMCommunicationContact> getCOMCommunicationContact() {
        return cOMCommunicationContact;
    }

    public SegmentGroup43 setCOMCommunicationContact(List<COMCommunicationContact> cOMCommunicationContact) {
        this.cOMCommunicationContact = cOMCommunicationContact;  return this;
    }
}