/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.IFTMAN;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.TPLTransportPlacement;    
import java.util.List;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup26 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private TPLTransportPlacement tPLTransportPlacement;
    private List<SegmentGroup27> segmentGroup27;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(tPLTransportPlacement != null) {
            nodeWriter.write("TPL");
            nodeWriter.write(delimiters.getField());
            tPLTransportPlacement.write(nodeWriter, delimiters);
        }
        if(segmentGroup27 != null && !segmentGroup27.isEmpty()) {
            for(SegmentGroup27 segmentGroup27Inst : segmentGroup27) {
                segmentGroup27Inst.write(nodeWriter, delimiters);
            }
        }
    }

    public TPLTransportPlacement getTPLTransportPlacement() {
        return tPLTransportPlacement;
    }

    public SegmentGroup26 setTPLTransportPlacement(TPLTransportPlacement tPLTransportPlacement) {
        this.tPLTransportPlacement = tPLTransportPlacement;  return this;
    }

    public List<SegmentGroup27> getSegmentGroup27() {
        return segmentGroup27;
    }

    public SegmentGroup26 setSegmentGroup27(List<SegmentGroup27> segmentGroup27) {
        this.segmentGroup27 = segmentGroup27;  return this;
    }
}