/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.COPARN;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.TMPTemperature;    
import org.milyn.edi.unedifact.d17a.common.RNGRangeDetails;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup12 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private TMPTemperature tMPTemperature;
    private RNGRangeDetails rNGRangeDetails;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(tMPTemperature != null) {
            nodeWriter.write("TMP");
            nodeWriter.write(delimiters.getField());
            tMPTemperature.write(nodeWriter, delimiters);
        }
        if(rNGRangeDetails != null) {
            nodeWriter.write("RNG");
            nodeWriter.write(delimiters.getField());
            rNGRangeDetails.write(nodeWriter, delimiters);
        }
    }

    public TMPTemperature getTMPTemperature() {
        return tMPTemperature;
    }

    public SegmentGroup12 setTMPTemperature(TMPTemperature tMPTemperature) {
        this.tMPTemperature = tMPTemperature;  return this;
    }

    public RNGRangeDetails getRNGRangeDetails() {
        return rNGRangeDetails;
    }

    public SegmentGroup12 setRNGRangeDetails(RNGRangeDetails rNGRangeDetails) {
        this.rNGRangeDetails = rNGRangeDetails;  return this;
    }
}