/**
 * This class was generated by Smooks EJC (http://www.smooks.org).
 */
package org.milyn.edi.unedifact.d17a.INSDES;

import java.io.Serializable;    
import org.milyn.smooks.edi.EDIWritable;    
import org.milyn.edi.unedifact.d17a.common.TODTermsOfDeliveryOrTransport;    
import java.util.List;    
import org.milyn.edi.unedifact.d17a.common.LOCPlaceLocationIdentification;    
import org.milyn.edi.unedifact.d17a.common.FTXFreeText;    
import java.io.Writer;    
import org.milyn.edisax.model.internal.Delimiters;    
import java.io.IOException;    

public class SegmentGroup5 implements Serializable, EDIWritable {

    private static final long serialVersionUID = 1L;

    private TODTermsOfDeliveryOrTransport tODTermsOfDeliveryOrTransport;
    private List<LOCPlaceLocationIdentification> lOCPlaceLocationIdentification;
    private List<FTXFreeText> fTXFreeText;

    public void write(Writer writer, Delimiters delimiters) throws IOException {
        
        Writer nodeWriter = writer;

        if(tODTermsOfDeliveryOrTransport != null) {
            nodeWriter.write("TOD");
            nodeWriter.write(delimiters.getField());
            tODTermsOfDeliveryOrTransport.write(nodeWriter, delimiters);
        }
        if(lOCPlaceLocationIdentification != null && !lOCPlaceLocationIdentification.isEmpty()) {
            for(LOCPlaceLocationIdentification lOCPlaceLocationIdentificationInst : lOCPlaceLocationIdentification) {
                nodeWriter.write("LOC");
                nodeWriter.write(delimiters.getField());
                lOCPlaceLocationIdentificationInst.write(nodeWriter, delimiters);
            }
        }
        if(fTXFreeText != null && !fTXFreeText.isEmpty()) {
            for(FTXFreeText fTXFreeTextInst : fTXFreeText) {
                nodeWriter.write("FTX");
                nodeWriter.write(delimiters.getField());
                fTXFreeTextInst.write(nodeWriter, delimiters);
            }
        }
    }

    public TODTermsOfDeliveryOrTransport getTODTermsOfDeliveryOrTransport() {
        return tODTermsOfDeliveryOrTransport;
    }

    public SegmentGroup5 setTODTermsOfDeliveryOrTransport(TODTermsOfDeliveryOrTransport tODTermsOfDeliveryOrTransport) {
        this.tODTermsOfDeliveryOrTransport = tODTermsOfDeliveryOrTransport;  return this;
    }

    public List<LOCPlaceLocationIdentification> getLOCPlaceLocationIdentification() {
        return lOCPlaceLocationIdentification;
    }

    public SegmentGroup5 setLOCPlaceLocationIdentification(List<LOCPlaceLocationIdentification> lOCPlaceLocationIdentification) {
        this.lOCPlaceLocationIdentification = lOCPlaceLocationIdentification;  return this;
    }

    public List<FTXFreeText> getFTXFreeText() {
        return fTXFreeText;
    }

    public SegmentGroup5 setFTXFreeText(List<FTXFreeText> fTXFreeText) {
        this.fTXFreeText = fTXFreeText;  return this;
    }
}