//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.6-01/24/2006 06:15 PM(kohsuke)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.01 at 01:03:46 PM CET 
//


package org.jvnet.jaxbhelp.structure.impl;

public class JAXBVersion {

    public final static java.lang.String version = "1.0.6";

}
