//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.22 at 09:38:48 AM CET 
//


package no.kith.xmlstds.eresept.m1._2013_10_08;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the no.kith.xmlstds.eresept.m1._2013_10_08 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: no.kith.xmlstds.eresept.m1._2013_10_08
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReseptDokLegemiddel }
     * 
     */
    public ReseptDokLegemiddel createReseptDokLegemiddel() {
        return new ReseptDokLegemiddel();
    }

    /**
     * Create an instance of {@link TypeReseptDok }
     * 
     */
    public TypeReseptDok createTypeReseptDok() {
        return new TypeReseptDok();
    }

    /**
     * Create an instance of {@link LegemiddelUtenMt }
     * 
     */
    public LegemiddelUtenMt createLegemiddelUtenMt() {
        return new LegemiddelUtenMt();
    }

    /**
     * Create an instance of {@link ReseptDokHandelsvare }
     * 
     */
    public ReseptDokHandelsvare createReseptDokHandelsvare() {
        return new ReseptDokHandelsvare();
    }

    /**
     * Create an instance of {@link Resept }
     * 
     */
    public Resept createResept() {
        return new Resept();
    }

    /**
     * Create an instance of {@link Instituert }
     * 
     */
    public Instituert createInstituert() {
        return new Instituert();
    }

    /**
     * Create an instance of {@link Organisasjon }
     * 
     */
    public Organisasjon createOrganisasjon() {
        return new Organisasjon();
    }

    /**
     * Create an instance of {@link Helseperson }
     * 
     */
    public Helseperson createHelseperson() {
        return new Helseperson();
    }

    /**
     * Create an instance of {@link EkspAnm }
     * 
     */
    public EkspAnm createEkspAnm() {
        return new EkspAnm();
    }

    /**
     * Create an instance of {@link Utlending }
     * 
     */
    public Utlending createUtlending() {
        return new Utlending();
    }

    /**
     * Create an instance of {@link EEA }
     * 
     */
    public EEA createEEA() {
        return new EEA();
    }

}
