//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.22 at 09:40:30 AM CET 
//


package no.kith.xmlstds.eresept.m1._2013_10_08;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Begrunnelse" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Produsent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DirektesoknadSlv" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "begrunnelse",
    "produsent",
    "direktesoknadSlv"
})
@XmlRootElement(name = "LegemiddelUtenMt")
public final class LegemiddelUtenMt {

    @XmlElement(name = "Begrunnelse", required = true)
    private final String begrunnelse;
    @XmlElement(name = "Produsent", required = true)
    private final String produsent;
    @XmlElement(name = "DirektesoknadSlv")
    private final boolean direktesoknadSlv;

    public LegemiddelUtenMt(final String begrunnelse, final String produsent, final boolean direktesoknadSlv) {
        this.begrunnelse = begrunnelse;
        this.produsent = produsent;
        this.direktesoknadSlv = direktesoknadSlv;
    }

    /**
     * Used by JAX-B
     * 
     */
    protected LegemiddelUtenMt() {
        this.begrunnelse = null;
        this.produsent = null;
        this.direktesoknadSlv = false;
    }

    /**
     * Gets the value of the begrunnelse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBegrunnelse() {
        return begrunnelse;
    }

    /**
     * Gets the value of the produsent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdusent() {
        return produsent;
    }

    /**
     * Gets the value of the direktesoknadSlv property.
     * 
     */
    public boolean isDirektesoknadSlv() {
        return direktesoknadSlv;
    }

    public static LegemiddelUtenMt.LegemiddelUtenMtBuilder legemiddelUtenMtBuilder() {
        return new LegemiddelUtenMt.LegemiddelUtenMtBuilder();
    }

    public static class LegemiddelUtenMtBuilder {

        private String begrunnelse;
        private String produsent;
        private boolean direktesoknadSlv;

        public LegemiddelUtenMt.LegemiddelUtenMtBuilder withBegrunnelse(final String begrunnelse) {
            this.begrunnelse = begrunnelse;
            return this;
        }

        public LegemiddelUtenMt.LegemiddelUtenMtBuilder withProdusent(final String produsent) {
            this.produsent = produsent;
            return this;
        }

        public LegemiddelUtenMt.LegemiddelUtenMtBuilder withDirektesoknadSlv(final boolean direktesoknadSlv) {
            this.direktesoknadSlv = direktesoknadSlv;
            return this;
        }

        public LegemiddelUtenMt build() {
            if (begrunnelse == null) {
                throw new NullPointerException("Required field 'begrunnelse' have to be assigned a value.");
            }
            if (produsent == null) {
                throw new NullPointerException("Required field 'produsent' have to be assigned a value.");
            }
            return new LegemiddelUtenMt(begrunnelse, produsent, direktesoknadSlv);
        }

    }

}
