//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.22 at 09:40:30 AM CET 
//


package no.kith.xmlstds.eresept.forskrivning._2013_10_08;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import no.kith.xmlstds.PQ;


/**
 * <p>Java class for typeDose complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeDose"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Mengde" type="{http://www.kith.no/xmlstds}PQ"/&gt;
 *         &lt;element name="Intervall" type="{http://www.kith.no/xmlstds}PQ" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2013-10-08}Infusjonshastighet" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeDose", propOrder = {
    "mengde",
    "intervall",
    "infusjonshastighet"
})
@XmlSeeAlso({
    DoseEtterBehov.class,
    DoseFastTidspunkt.class
})
public class TypeDose {

    @XmlElement(name = "Mengde", required = true)
    private final PQ mengde;
    @XmlElement(name = "Intervall")
    private final PQ intervall;
    @XmlElement(name = "Infusjonshastighet")
    private final Infusjonshastighet infusjonshastighet;

    public TypeDose(final PQ mengde, final PQ intervall, final Infusjonshastighet infusjonshastighet) {
        this.mengde = mengde;
        this.intervall = intervall;
        this.infusjonshastighet = infusjonshastighet;
    }

    /**
     * Used by JAX-B
     * 
     */
    protected TypeDose() {
        this.mengde = null;
        this.intervall = null;
        this.infusjonshastighet = null;
    }

    /**
     * Gets the value of the mengde property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getMengde() {
        return mengde;
    }

    /**
     * Gets the value of the intervall property.
     * 
     * @return
     *     possible object is
     *     {@link PQ }
     *     
     */
    public PQ getIntervall() {
        return intervall;
    }

    /**
     * Gets the value of the infusjonshastighet property.
     * 
     * @return
     *     possible object is
     *     {@link Infusjonshastighet }
     *     
     */
    public Infusjonshastighet getInfusjonshastighet() {
        return infusjonshastighet;
    }

    public static TypeDose.TypeDoseBuilder typeDoseBuilder() {
        return new TypeDose.TypeDoseBuilder();
    }

    public static class TypeDoseBuilder {

        private PQ mengde;
        private PQ intervall;
        private Infusjonshastighet infusjonshastighet;

        public TypeDose.TypeDoseBuilder withMengde(final PQ mengde) {
            this.mengde = mengde;
            return this;
        }

        public TypeDose.TypeDoseBuilder withIntervall(final PQ intervall) {
            this.intervall = intervall;
            return this;
        }

        public TypeDose.TypeDoseBuilder withInfusjonshastighet(final Infusjonshastighet infusjonshastighet) {
            this.infusjonshastighet = infusjonshastighet;
            return this;
        }

        public TypeDose build() {
            if (mengde == null) {
                throw new NullPointerException("Required field 'mengde' have to be assigned a value.");
            }
            return new TypeDose(mengde, intervall, infusjonshastighet);
        }

    }

}
