//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.22 at 09:40:30 AM CET 
//


package no.kith.xmlstds.eresept.forskrivning._2013_10_08;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RefByttegruppe" type="{http://www.w3.org/2001/XMLSchema}IDREF"/&gt;
 *         &lt;element name="GyldigFraDato" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="GyldigTilDato" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "refByttegruppe",
    "gyldigFraDato",
    "gyldigTilDato"
})
@XmlRootElement(name = "PakningByttegruppe")
public final class PakningByttegruppe {

    @XmlElement(name = "RefByttegruppe", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    private final Object refByttegruppe;
    @XmlElement(name = "GyldigFraDato")
    @XmlSchemaType(name = "date")
    private final XMLGregorianCalendar gyldigFraDato;
    @XmlElement(name = "GyldigTilDato")
    @XmlSchemaType(name = "date")
    private final XMLGregorianCalendar gyldigTilDato;

    public PakningByttegruppe(final Object refByttegruppe, final XMLGregorianCalendar gyldigFraDato, final XMLGregorianCalendar gyldigTilDato) {
        this.refByttegruppe = refByttegruppe;
        this.gyldigFraDato = gyldigFraDato;
        this.gyldigTilDato = gyldigTilDato;
    }

    /**
     * Used by JAX-B
     * 
     */
    protected PakningByttegruppe() {
        this.refByttegruppe = null;
        this.gyldigFraDato = null;
        this.gyldigTilDato = null;
    }

    /**
     * Gets the value of the refByttegruppe property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRefByttegruppe() {
        return refByttegruppe;
    }

    /**
     * Gets the value of the gyldigFraDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGyldigFraDato() {
        return gyldigFraDato;
    }

    /**
     * Gets the value of the gyldigTilDato property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGyldigTilDato() {
        return gyldigTilDato;
    }

    public static PakningByttegruppe.PakningByttegruppeBuilder pakningByttegruppeBuilder() {
        return new PakningByttegruppe.PakningByttegruppeBuilder();
    }

    public static class PakningByttegruppeBuilder {

        private Object refByttegruppe;
        private XMLGregorianCalendar gyldigFraDato;
        private XMLGregorianCalendar gyldigTilDato;

        public PakningByttegruppe.PakningByttegruppeBuilder withRefByttegruppe(final Object refByttegruppe) {
            this.refByttegruppe = refByttegruppe;
            return this;
        }

        public PakningByttegruppe.PakningByttegruppeBuilder withGyldigFraDato(final XMLGregorianCalendar gyldigFraDato) {
            this.gyldigFraDato = gyldigFraDato;
            return this;
        }

        public PakningByttegruppe.PakningByttegruppeBuilder withGyldigTilDato(final XMLGregorianCalendar gyldigTilDato) {
            this.gyldigTilDato = gyldigTilDato;
            return this;
        }

        public PakningByttegruppe build() {
            if (refByttegruppe == null) {
                throw new NullPointerException("Required field 'refByttegruppe' have to be assigned a value.");
            }
            return new PakningByttegruppe(refByttegruppe, gyldigFraDato, gyldigTilDato);
        }

    }

}
