//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.12.22 at 09:40:30 AM CET 
//


package no.kith.xmlstds.eresept.forskrivning._2013_10_08;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import no.kith.xmlstds.TS;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Starttidspunkt" type="{http://www.kith.no/xmlstds}TS" minOccurs="0"/&gt;
 *         &lt;element name="Sluttidspunkt" type="{http://www.kith.no/xmlstds}TS" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2013-10-08}Doseringsregel" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2013-10-08}DoseFastTidspunkt" maxOccurs="unbounded"/&gt;
 *           &lt;element ref="{http://www.kith.no/xmlstds/eresept/forskrivning/2013-10-08}DoseEtterBehov" maxOccurs="unbounded"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "starttidspunkt",
    "sluttidspunkt",
    "doseringsregel",
    "doseFastTidspunkt",
    "doseEtterBehov"
})
@XmlRootElement(name = "Dosering")
public final class Dosering {

    @XmlElement(name = "Starttidspunkt")
    private final TS starttidspunkt;
    @XmlElement(name = "Sluttidspunkt")
    private final TS sluttidspunkt;
    @XmlElement(name = "Doseringsregel")
    private final Doseringsregel doseringsregel;
    @XmlElement(name = "DoseFastTidspunkt")
    private final List<DoseFastTidspunkt> doseFastTidspunkt;
    @XmlElement(name = "DoseEtterBehov")
    private final List<DoseEtterBehov> doseEtterBehov;

    public Dosering(final TS starttidspunkt, final TS sluttidspunkt, final Doseringsregel doseringsregel, final List<DoseFastTidspunkt> doseFastTidspunkt, final List<DoseEtterBehov> doseEtterBehov) {
        this.starttidspunkt = starttidspunkt;
        this.sluttidspunkt = sluttidspunkt;
        this.doseringsregel = doseringsregel;
        if (doseFastTidspunkt == null) {
            this.doseFastTidspunkt = null;
        } else {
            this.doseFastTidspunkt = new ArrayList<DoseFastTidspunkt>(doseFastTidspunkt);
        }
        if (doseEtterBehov == null) {
            this.doseEtterBehov = null;
        } else {
            this.doseEtterBehov = new ArrayList<DoseEtterBehov>(doseEtterBehov);
        }
    }

    /**
     * Used by JAX-B
     * 
     */
    protected Dosering() {
        this.starttidspunkt = null;
        this.sluttidspunkt = null;
        this.doseringsregel = null;
        this.doseFastTidspunkt = null;
        this.doseEtterBehov = null;
    }

    /**
     * Gets the value of the starttidspunkt property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getStarttidspunkt() {
        return starttidspunkt;
    }

    /**
     * Gets the value of the sluttidspunkt property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getSluttidspunkt() {
        return sluttidspunkt;
    }

    /**
     * Gets the value of the doseringsregel property.
     * 
     * @return
     *     possible object is
     *     {@link Doseringsregel }
     *     
     */
    public Doseringsregel getDoseringsregel() {
        return doseringsregel;
    }

    public List<DoseFastTidspunkt> getDoseFastTidspunkt() {
        List<DoseFastTidspunkt> ret;
        if (doseFastTidspunkt == null) {
            ret = Collections.emptyList();
        } else {
            ret = Collections.unmodifiableList(doseFastTidspunkt);
        }
        return ret;
    }

    public List<DoseEtterBehov> getDoseEtterBehov() {
        List<DoseEtterBehov> ret;
        if (doseEtterBehov == null) {
            ret = Collections.emptyList();
        } else {
            ret = Collections.unmodifiableList(doseEtterBehov);
        }
        return ret;
    }

    public static Dosering.DoseringBuilder doseringBuilder() {
        return new Dosering.DoseringBuilder();
    }

    public static class DoseringBuilder {

        private TS starttidspunkt;
        private TS sluttidspunkt;
        private Doseringsregel doseringsregel;
        private List<DoseFastTidspunkt> doseFastTidspunkt = new ArrayList<DoseFastTidspunkt>();
        private List<DoseEtterBehov> doseEtterBehov = new ArrayList<DoseEtterBehov>();

        public Dosering.DoseringBuilder withStarttidspunkt(final TS starttidspunkt) {
            this.starttidspunkt = starttidspunkt;
            return this;
        }

        public Dosering.DoseringBuilder withSluttidspunkt(final TS sluttidspunkt) {
            this.sluttidspunkt = sluttidspunkt;
            return this;
        }

        public Dosering.DoseringBuilder withDoseringsregel(final Doseringsregel doseringsregel) {
            this.doseringsregel = doseringsregel;
            return this;
        }

        public Dosering.DoseringBuilder withDoseFastTidspunkt(final List<DoseFastTidspunkt> doseFastTidspunkt) {
            this.doseFastTidspunkt = doseFastTidspunkt;
            return this;
        }

        public Dosering.DoseringBuilder addDoseFastTidspunkt(final DoseFastTidspunkt doseFastTidspunkt) {
            this.doseFastTidspunkt.add(doseFastTidspunkt);
            return this;
        }

        public Dosering.DoseringBuilder withDoseEtterBehov(final List<DoseEtterBehov> doseEtterBehov) {
            this.doseEtterBehov = doseEtterBehov;
            return this;
        }

        public Dosering.DoseringBuilder addDoseEtterBehov(final DoseEtterBehov doseEtterBehov) {
            this.doseEtterBehov.add(doseEtterBehov);
            return this;
        }

        public Dosering build() {
            return new Dosering(starttidspunkt, sluttidspunkt, doseringsregel, doseFastTidspunkt, doseEtterBehov);
        }

    }

}
